# -*- fundamental -*-
#
# The long dictionary constants in this file cause emacs Python mode to
# hang for seconds or minutes every now and then, and thus editing in
# fundamental mode is much more convenient...

# Finnish noun declension definitions.  Possessive suffixes are also defined
# in this file.  These are also used for inflecting certain verb forms.
#
# This file defines comparatives, but in general it is better to use known
# comparative forms (e.g., as extracted from Wiktionary or learned otherwise),
# as some derivations are irregular.  The comparative rules here have not
# been extensively tested.

# Variants with -poss are used if a possessive suffix or clitic follows.
# Variants with -clitic are used if a clitic but no possessive suffix follows.
# Otherwise defaults to a the rule given by the form name.  The value may
# be either a string or a list of strings, most preferred one first, or None
# if that form does not exist for the declension.
#
# Special chracters in rules include:
#   digit - use value of that argument from the declension/conjugation
#   9 - takes partitive singular vowel from par_sg_a or last deleted char
#   O - converted to o or ö based on vowel harmony
#   U - converted to u or y based on vowel harmony
#   A - converted to a or ä based on vowel harmony (usually digit used instead)
#   D - converted to D or previous character after any of: lmnr
#   @ - used for illative singular (usually vowel lengthening + special rules)
#   - - deletes previos char but it is still used for vowel harmony
#   / - deletes the char before last, but it is still used for vowel harmony
#
# Copyright (c) 2018 Tatu Ylonen.  See COPYING and https://ylonen.org

decl_name_map = {
    "fi-decl-kauneus": "fi-decl-kalleus",
    "fi-decl-nuori": "fi-decl-pieni",
}

noun_decls = {
    "fi-decl-valo": {
    	"nargs": 5,
	"default": {"4": "o"},
        "": "124",
        "gen-sg": "134n",
        "gen-sg-poss": "124",
        "ptv-sg": "1245",
        "ine-sg": "134ss5",
        "ela-sg": "134st5",
        "ill-sg": "124@n",
        "ill-sg-poss": "124@",
        "ade-sg": "134ll5",
        "abl-sg": "134lt5",
        "all-sg": "134lle",
        "ess-sg": "124n5",
        "tra-sg": "134ksi",
        "tra-sg-poss": "134kse",
        "ins-sg": None,
        "abe-sg": "134tt5",
        "nom-pl": "134t",
        "nom-pl-poss": "124",
        "gen-pl": "124jen",
        "gen-pl-poss": "124je",
        "ptv-pl": "124j5",
        "ine-pl": "134iss5",
        "ela-pl": "134ist5",
        "ill-pl": "124ihin",
        "ill-pl-poss": "124ihi",
        "ade-pl": "134ill5",
        "abl-pl": "134ilt5",
        "all-pl": "134ille",
        "ess-pl": "124in5",
        "tra-pl": "134iksi",
        "tra-pl-poss": "134ikse",
        "ins-pl": "134in",
        "ins-pl-poss": None,
        "abe-pl": "134itt5",
        "cmt": "124ine",
        "hkO": "134hk5-O",
        "comp": "134mpi",
        "sup": "134in",
	"manner": "134sti",
        "comp-manner": "134mmin",
        "sup-manner": "134immin",
    },
    "fi-decl-palvelu": {
    	"nargs": 2,
        "": "1",
        "gen-sg": "1n",
        "gen-sg-poss": "1",
        "ptv-sg": "12",
        "ine-sg": "1ss2",
        "ela-sg": "1st2",
        "ill-sg": "1@n",
        "ill-sg-poss": "1@",
        "ade-sg": "1ll2",
        "abl-sg": "1lt2",
        "all-sg": "1lle",
        "ess-sg": "1n2",
        "tra-sg": "1ksi",
        "tra-sg-poss": "1kse",
        "ins-sg": None,
        "abe-sg": "1tt2",
        "nom-pl": "1t",
        "nom-pl-poss": "1",
        "gen-pl": ["1jen", "1iden", "1itten"],
        "gen-pl-poss": ["1je", "1ide", "1itte"],
        "ptv-pl": ["1j2", "1it2"],
        "ine-pl": "1iss2",
        "ela-pl": "1ist2",
        "ill-pl": "1ihin",
        "ill-pl-poss": "1ihi",
        "ade-pl": "1ill2",
        "abl-pl": "1ilt2",
        "all-pl": "1ille",
        "ess-pl": "1in2",
        "tra-pl": "1iksi",
        "tra-pl-poss": "1ikse",
        "ins-pl": "1in",
        "ins-pl-poss": None,
        "abe-pl": "1itt2",
        "cmt": "1ine",
        "hkO": "1hk2-O",
        "comp": "1mpi",
        "sup": "1in",
	"manner": "1sti",
        "comp-manner": "1mmin",
        "sup-manner": "1immin",
    },
    "fi-decl-valtio": {
    	"nargs": 2,
        "": "1",
        "gen-sg": "1n",
        "gen-sg-poss": "1",
        "ptv-sg": "1t2",
        "ine-sg": "1ss2",
        "ela-sg": "1st2",
        "ill-sg": "1@n",
        "ill-sg-poss": "1@",
        "ade-sg": "1ll2",
        "abl-sg": "1lt2",
        "all-sg": "1lle",
        "ess-sg": "1n2",
        "tra-sg": "1ksi",
        "tra-sg-poss": "1kse",
        "ins-sg": None,
        "abe-sg": "1tt2",
        "nom-pl": "1t",
        "nom-pl-poss": "1",
        "gen-pl": ["1iden", "1itten"],
        "gen-pl-poss": ["1ide", "1itte"],
        "ptv-pl": "1it2",
        "ine-pl": "1iss2",
        "ela-pl": "1ist2",
        "ill-pl": "1ihin",
        "ill-pl-poss": "1ihi",
        "ade-pl": "1ill2",
        "abl-pl": "1ilt2",
        "all-pl": "1ille",
        "ess-pl": "1in2",
        "tra-pl": "1iksi",
        "tra-pl-poss": "1ikse",
        "ins-pl": "1in",
        "ins-pl-poss": None,
        "abe-pl": "1itt2",
        "cmt": "1ine",
        "hkO": "1hk2-O",
        "comp": "1mpi",
        "sup": "1in",
	"manner": "1sti",
        "comp-manner": "1mmin",
        "sup-manner": "1immin",
    },
    "fi-decl-laatikko": {
    	"nargs": 5,
	"default": {"4": "o"},
        "": "124",
        "gen-sg": "134n",
        "gen-sg-poss": "124",
        "ptv-sg": "1245",
        "ine-sg": "134ss5",
        "ela-sg": "134st5",
        "ill-sg": "124@n",
        "ill-sg-poss": "124@",
        "ade-sg": "134ll5",
        "abl-sg": "134lt5",
        "all-sg": "134lle",
        "ess-sg": "124n5",
        "tra-sg": "134ksi",
        "tra-sg-poss": "134kse",
        "ins-sg": None,
        "abe-sg": "134tt5",
        "nom-pl": "134t",
        "nom-pl-poss": "124",
        "gen-pl": ["124jen", "134iden", "134itten"],
        "gen-pl-poss": ["124je", "134ide", "134itte"],
        "ptv-pl": ["124j5", "134it5"],
        "ine-pl": "134iss5",
        "ela-pl": "134ist5",
        "ill-pl": ["124ihin", "134ihin"],
        "ill-pl-poss": ["124ihi", "134ihi"],
        "ade-pl": "134ill5",
        "abl-pl": "134ilt5",
        "all-pl": "134ille",
        "ess-pl": "124in5",
        "tra-pl": "134iksi",
        "tra-pl-poss": "134ikse",
        "ins-pl": "134in",
        "ins-pl-poss": None,
        "abe-pl": "134itt5",
        "cmt": "124ine",
        "hkO": "134hk5-O",
        "comp": "134mpi",
        "sup": "124in",
	"manner": "134sti",
        "comp-manner": "134mmin",
        "sup-manner": "134immin",
    },
    "fi-decl-risti": {
    	"nargs": 4,
        "": "12i",
        "gen-sg": "13in",
        "gen-sg-poss": "12i",
        "ptv-sg": "12i4",
        "ine-sg": "13iss4",
        "ela-sg": "13ist4",
        "ill-sg": "12iin",
        "ill-sg-poss": "12ii",
        "ade-sg": "13ill4",
        "abl-sg": "13ilt4",
        "all-sg": "13ille",
        "ess-sg": "12in4",
        "tra-sg": "13iksi",
        "tra-sg-poss": "13ikse",
        "ins-sg": None,
        "abe-sg": "13itt4",
        "nom-pl": "13it",
        "nom-pl-poss": "12i",
        "gen-pl": "12ien",
        "gen-pl-poss": "12ie",
        "ptv-pl": "12ej4",
        "ine-pl": "13eiss4",
        "ela-pl": "13eist4",
        "ill-pl": "12eihin",
        "ill-pl-poss": "12eihi",
        "ade-pl": "13eill4",
        "abl-pl": "13eilt4",
        "all-pl": "13eille",
        "ess-pl": "12ein4",
        "tra-pl": "13eiksi",
        "tra-pl-poss": "13eikse",
        "ins-pl": "13ein",
        "ins-pl-poss": None,
        "abe-pl": "13eitt4",
        "cmt": "12eine",
        "hkO": "13hk4-O",
        "comp": "13impi",
        "sup": "13ein",
	"manner": "134isti",
        "comp-manner": "134immin",
        "sup-manner": "134eimmin",
    },
    "fi-decl-paperi": {
    	"nargs": 2,
        "": "1i",
        "gen-sg": "1in",
        "gen-sg-poss": "1i",
        "ptv-sg": "1i2",
        "ine-sg": "1iss2",
        "ela-sg": "1ist2",
        "ill-sg": "1iin",
        "ill-sg-poss": "1ii",
        "ade-sg": "1ill2",
        "abl-sg": "1ilt2",
        "all-sg": "1ille",
        "ess-sg": "1in2",
        "tra-sg": "1iksi",
        "tra-sg-poss": "1ikse",
        "ins-sg": None,
        "abe-sg": "1itt2",
        "nom-pl": "1it",
        "nom-pl-poss": "1i",
        "gen-pl": ["1ien", "1eiden", "1eitten"],
        "gen-pl-poss": ["1ie", "1eide", "1eitte"],
        "ptv-pl": ["1ej2", "1eit2"],
        "ine-pl": "1eiss2",
        "ela-pl": "1eist2",
        "ill-pl": "1eihin",
        "ill-pl-poss": "1eihi",
        "ade-pl": "1eill2",
        "abl-pl": "1eilt2",
        "all-pl": "1eille",
        "ess-pl": "1ein2",
        "tra-pl": "1eiksi",
        "tra-pl-poss": "1eikse",
        "ins-pl": "1ein",
        "ins-pl-poss": None,
        "abe-pl": "1eitt2",
        "cmt": "1eine",
        "hkO": "1ihk2-O",
        "comp": "1impi",
        "sup": "1ein",
	"manner": "1isti",
        "comp-manner": "1immin",
        "sup-manner": "1eimmin",
    },
    "fi-decl-ovi": {
    	"nargs": 4,
        "": "12i",
        "-poss": "12e",
        "gen-sg": "13en",
        "gen-sg-poss": "12e",
        "ptv-sg": "12e4",
        "ine-sg": "13ess4",
        "ela-sg": "13est4",
        "ill-sg": "12een",
        "ill-sg-poss": "12ee",
        "ade-sg": "13ell4",
        "abl-sg": "13elt4",
        "all-sg": "13elle",
        "ess-sg": "12en4",
        "tra-sg": "13eksi",
        "tra-sg-poss": "13ekse",
        "ins-sg": None,
        "abe-sg": "13ett4",
        "nom-pl": "13et",
        "nom-pl-poss": "12e",
        "gen-pl": "12ien",
        "gen-pl-poss": "12ie",
        "ptv-pl": "12i4",
        "ine-pl": "13iss4",
        "ela-pl": "13ist4",
        "ill-pl": "12iin",
        "ill-pl-poss": "12ii",
        "ade-pl": "13ill4",
        "abl-pl": "13ilt4",
        "all-pl": "13ille",
        "ess-pl": "12in4",
        "tra-pl": "13iksi",
        "tra-pl-poss": "13ikse",
        "ins-pl": "13in",
        "ins-pl-poss": None,
        "abe-pl": "13itt4",
        "cmt": "12ine",
        "hkO": "13ehk4-O",
        "comp": "13empi",
        "sup": "13in",
	"manner": "13esti",
        "comp-manner": "13emmin",
        "sup-manner": "13immin",
    },
    "fi-decl-nalle": {
    	"nargs": 4,
        "": "12e",
        "gen-sg": "13en",
        "gen-sg-poss": "12e",
        "ptv-sg": "12e4",
        "ine-sg": "13ess4",
        "ela-sg": "13est4",
        "ill-sg": "12een",
        "ill-sg-poss": "12ee",
        "ade-sg": "13ell4",
        "abl-sg": "13elt4",
        "all-sg": "13elle",
        "ess-sg": "12en4",
        "tra-sg": "13eksi",
        "tra-sg-poss": "13ekse",
        "ins-sg": None,
        "abe-sg": "13ett4",
        "nom-pl": "13et",
        "nom-pl-poss": "12e",
        "gen-pl": ["12ejen", "12ein", "12ien"],  # latter two rare, last ?
        "gen-pl-poss": ["12eje", "12ei", "12ie"],  # last 2 rare, last ?
        "ptv-pl": "12ej4",
        "ine-pl": "13eiss4",
        "ela-pl": "13eist4",
        "ill-pl": "12eihin",
        "ill-pl-poss": "12eihi",
        "ade-pl": "13eill4",
        "abl-pl": "13eilt4",
        "all-pl": "13eille",
        "ess-pl": "12ein4",
        "tra-pl": "13eiksi",
        "tra-pl-poss": "13eikse",
        "ins-pl": "13ein",
        "ins-pl-poss": None,
        "abe-pl": "13eitt4",
        "cmt": "12eine",
        "hkO": "12ehk4-O",
        "comp": "13empi",
        "sup": "13ein",
	"manner": "13esti",
        "comp-manner": "13emmin",
        "sup-manner": "13eimmin",
    },
    "fi-decl-kala": {
    	"nargs": 4,
	"default": {"4": "a"},
        "": "124",
        "gen-sg": "134n",
        "gen-sg-poss": "124",
        "ptv-sg": "1244",
        "ine-sg": "134ss4",
        "ela-sg": "134st4",
        "ill-sg": "124@n",
        "ill-sg-poss": "124@",
        "ade-sg": "134ll4",
        "abl-sg": "134lt4",
        "all-sg": "134lle",
        "ess-sg": "124n4",
        "tra-sg": "134ksi",
        "tra-sg-poss": "134kse",
        "ins-sg": None,
        "abe-sg": "134tt4",
        "nom-pl": "134t",
        "nom-pl-poss": "124",
        "gen-pl": ["124-Ojen", "124in"],  # Latter rare
        "gen-pl-poss": ["124-Oje", "124i"],  # Latter rare
        "ptv-pl": "124-Oj4",
        "ine-pl": "134-Oiss4",
        "ela-pl": "134-Oist4",
        "ill-pl": "124-Oihin",
        "ill-pl-poss": "124-Oihi",
        "ade-pl": "134-Oill4",
        "abl-pl": "134-Oilt4",
        "all-pl": "134-Oille",
        "ess-pl": "124-Oin4",
        "tra-pl": "134-Oiksi",
        "tra-pl-poss": "134-Oikse",
        "ins-pl": "134-Oin",
        "ins-pl-poss": None,
        "abe-pl": "134-Oitt4",
        "cmt": "124-Oine",
        "hkO": "134hkO",
        "comp": "134mpi",
        "sup": "134-Oin",
	"manner": "134sti",
        "comp-manner": "134mmin",
        "sup-manner": "134-Oimmin",
    },
    "fi-decl-koira": {
    	"nargs": 4,
	"default": {"4": "a"},
        "": "124",
        "gen-sg": "134n",
        "gen-sg-poss": "124",
        "ptv-sg": "1244",
        "ine-sg": "134ss4",
        "ela-sg": "134st4",
        "ill-sg": "124@n",
        "ill-sg-poss": "124@",
        "ade-sg": "134ll4",
        "abl-sg": "134lt4",
        "all-sg": "134lle",
        "ess-sg": "124n4",
        "tra-sg": "134ksi",
        "tra-sg-poss": "134kse",
        "ins-sg": None,
        "abe-sg": "134tt4",
        "nom-pl": "134t",
        "nom-pl-poss": "124",
        "gen-pl": ["12ien", "124in"],  # Latter rare
        "gen-pl-poss": ["12ie"],
        "ptv-pl": "12i4",
        "ine-pl": "13iss4",
        "ela-pl": "13ist4",
        "ill-pl": "12iin",
        "ill-pl-poss": "12ii",
        "ade-pl": "13ill4",
        "abl-pl": "13ilt4",
        "all-pl": "13ille",
        "ess-pl": "12in4",
        "tra-pl": "13iksi",
        "tra-pl-poss": "13ikse",
        "ins-pl": "13in",
        "ins-pl-poss": None,
        "abe-pl": "13itt4",
        "cmt": "12ine",
        "hkO": "134hkO",
        "comp": "134mpi",
        "sup": "13in",
	"manner": "134sti",
        "comp-manner": "134mmin",
        "sup-manner": "13immin",
    },
    "fi-decl-omena": {
    	"nargs": 2,
	"default": {"2": "a"},
        "": "12",
        "gen-sg": "12n",
        "gen-sg-poss": "12",
        "ptv-sg": "122",
        "ine-sg": "12ss2",
        "ela-sg": "12st2",
        "ill-sg": "12@n",
        "ill-sg-poss": "12@",
        "ade-sg": "12ll2",
        "abl-sg": "12lt2",
        "all-sg": "12lle",
        "ess-sg": "12n2",
        "tra-sg": "12ksi",
        "tra-sg-poss": "12kse",
        "ins-sg": None,
        "abe-sg": "12tt2",
        "nom-pl": "12t",
        "nom-pl-poss": "12",
        "gen-pl": ["1ien", "12-Oiden", "12-Oitten",
                   "12-Ojen", "12in"],  # Latter two rare
        "gen-pl-poss": ["1ie", "12-Oide", "12-Oitte", "12-Oje"],
        "ptv-pl": ["1i2", "12-Oit2", "12-Oj2"],
        "ine-pl": ["12-Oiss2", "1iss2"],
        "ela-pl": ["12-Oist2", "1ist2"],
        "ill-pl": ["12-Oihin", "1iin"],
        "ill-pl-poss": ["12-Oihi", "1ii"],
        "ade-pl": ["12-Oill2", "1ill2"],
        "abl-pl": ["12-Oilt2", "1ilt2"],
        "all-pl": ["12-Oille", "1ille"],
        "ess-pl": ["12-Oin2", "1in2"],
        "tra-pl": ["12-Oiksi", "1iksi"],
        "tra-pl-poss": ["12-Oikse", "1ikse"],
        "ins-pl": ["12-Oin", "1in"],
        "ins-pl-poss": None,
        "abe-pl": ["12-Oitt2", "1itt2"],
        "cmt": ["12-Oine", "1ine"],
        "hkO": "12hkO",
        "comp": "12mpi",
        "sup": ["12-Oin", "12in"],
	"manner": "12sti",
        "comp-manner": "12mmin",
        "sup-manner": ["12-Oimmin", "1immin"],
    },
    "fi-decl-kulkija": {
    	"nargs": 2,
	"default": {"2": "a"},
        "": "12",
        "gen-sg": "12n",
        "gen-sg-poss": "12",
        "ptv-sg": "122",
        "ine-sg": "12ss2",
        "ela-sg": "12st2",
        "ill-sg": "12@n",
        "ill-sg-poss": "12@",
        "ade-sg": "12ll2",
        "abl-sg": "12lt2",
        "all-sg": "12lle",
        "ess-sg": "12n2",
        "tra-sg": "12ksi",
        "tra-sg-poss": "12kse",
        "ins-sg": None,
        "abe-sg": "12tt2",
        "nom-pl": "12t",
        "nom-pl-poss": "12",
        "gen-pl": ["12-Oiden", "12-Oitten", "12in"],  # Last rare
        "gen-pl-poss": ["12-Oide", "12-Oitte", "12i"],
        "ptv-pl": ["12-Oit2"],
        "ine-pl": ["12-Oiss2"],
        "ela-pl": ["12-Oist2"],
        "ill-pl": ["12-Oihin"],
        "ill-pl-poss": ["12-Oihi"],
        "ade-pl": ["12-Oill2"],
        "abl-pl": ["12-Oilt2"],
        "all-pl": ["12-Oille"],
        "ess-pl": ["12-Oin2"],
        "tra-pl": ["12-Oiksi"],
        "tra-pl-poss": ["12-Oikse"],
        "ins-pl": ["12-Oin"],
        "ins-pl-poss": None,
        "abe-pl": ["12-Oitt2"],
        "cmt": ["12-Oine"],
        "hkO": "12hkO",
        "comp": "12mpi",
        "sup": "12-Oin",
	"manner": "12sti",
        "comp-manner": "12mmin",
        "sup-manner": "12-Oimmin",
    },
    "fi-decl-katiska": {
    	"nargs": 2,
	"default": {"2": "a"},
        "": "12",
        "gen-sg": "12n",
        "gen-sg-poss": "12",
        "ptv-sg": "122",
        "ine-sg": "12ss2",
        "ela-sg": "12st2",
        "ill-sg": "12@n",
        "ill-sg-poss": "12@",
        "ade-sg": "12ll2",
        "abl-sg": "12lt2",
        "all-sg": "12lle",
        "ess-sg": "12n2",
        "tra-sg": "12ksi",
        "tra-sg-poss": "12kse",
        "ins-sg": None,
        "abe-sg": "12tt2",
        "nom-pl": "12t",
        "nom-pl-poss": "12",
        "gen-pl": ["12-Oiden", "12-Oitten",
                   "12-Ojen", "12in"],  # Last rare
        "gen-pl-poss": ["12-Oide", "12-Oitte",
                   "12-Oje", "12i"],  # Last rare
        "ptv-pl": ["12-Oit2", "12-Oj2"],
        "ine-pl": ["12-Oiss2"],
        "ela-pl": ["12-Oist2"],
        "ill-pl": ["12-Oihin"],
        "ill-pl-poss": ["12-Oihi"],
        "ade-pl": ["12-Oill2"],
        "abl-pl": ["12-Oilt2"],
        "all-pl": ["12-Oille"],
        "ess-pl": ["12-Oin2"],
        "tra-pl": ["12-Oiksi"],
        "tra-pl-poss": ["12-Oikse"],
        "ins-pl": ["12-Oin"],
        "ins-pl-poss": None,
        "abe-pl": ["12-Oitt2"],
        "cmt": ["12-Oine"],
        "hkO": "12hkO",
        "comp": "12mpi",
        "sup": "12-Oin",
	"manner": "12sti",
        "comp-manner": "12mmin",
        "sup-manner": "12-Oimmin",
    },
    "fi-decl-solakka": {
    	"nargs": 4,
	"default": {"4": "a"},
        "": "124",
        "gen-sg": "134n",
        "gen-sg-poss": "124",
        "ptv-sg": "1244",
        "ine-sg": "134ss4",
        "ela-sg": "134st4",
        "ill-sg": "124@n",
        "ill-sg-poss": "124@",
        "ade-sg": "134ll4",
        "abl-sg": "134lt4",
        "all-sg": "134lle",
        "ess-sg": "124n4",
        "tra-sg": "134ksi",
        "tra-sg-poss": "134kse",
        "ins-sg": None,
        "abe-sg": "134tt4",
        "nom-pl": "134t",
        "nom-pl-poss": "124",
        "gen-pl": ["134-Oiden", "134-Oitten", "124-Ojen",
                   "124in"],  # Last rare
        "gen-pl-poss": ["134-Oide", "134-Oitte", "124-Oje",
                        "124i"],  # Last rare
        "ptv-pl": ["134-Oit4", "124-Oj4"],
        "ine-pl": "134-Oiss4",
        "ela-pl": "134-Oist4",
        "ill-pl": ["134-Oihin", "124-Oihin"],
        "ill-pl-poss": ["134-Oihi", "124-Oihi"],
        "ade-pl": "134-Oill4",
        "abl-pl": "134-Oilt4",
        "all-pl": "134-Oille",
        "ess-pl": "124-Oin4",
        "tra-pl": "134-Oiksi",
        "tra-pl-poss": "134-Oikse",
        "ins-pl": "134-Oin",
        "ins-pl-poss": None,
        "abe-pl": "134-Oitt4",
        "cmt": "124-Oine",
        "hkO": "134hkO",
        "comp": "134mpi",
        "sup": "134-Oin",
	"manner": "134sti",
        "comp-manner": "134mmin",
        "sup-manner": "134-Oimmin",
    },
    "fi-decl-korkea": {
    	"nargs": 2,
	"default": {"2": "a"},
        "": "12",
        "gen-sg": "12n",
        "gen-sg-poss": "12",
        "ptv-sg": ["122", "12t2"],
        "ine-sg": "12ss2",
        "ela-sg": "12st2",
        "ill-sg": "12@n",
        "ill-sg-poss": "12@",
        "ade-sg": "12ll2",
        "abl-sg": "12lt2",
        "all-sg": "12lle",
        "ess-sg": "12n2",
        "tra-sg": "12ksi",
        "tra-sg-poss": "12kse",
        "ins-sg": None,
        "abe-sg": "12tt2",
        "nom-pl": "12t",
        "nom-pl-poss": "12",
        "gen-pl": ["1iden", "1itten", "12in"],  # Last rare
        "gen-pl-poss": ["1ide", "1itte", "12i"],  # Last rare
        "ptv-pl": ["1it2"],
        "ine-pl": ["1iss2"],
        "ela-pl": ["1ist2"],
        "ill-pl": ["1isiin", "1ihin"],
        "ill-pl-poss": ["1isii", "1ihi"],
        "ade-pl": ["1ill2"],
        "abl-pl": ["1ilt2"],
        "all-pl": ["1ille"],
        "ess-pl": ["1in2"],
        "tra-pl": ["1iksi"],
        "tra-pl-poss": ["1ikse"],
        "ins-pl": ["1in"],
        "ins-pl-poss": None,
        "abe-pl": ["1itt2"],
        "cmt": ["1ine"],
        "hkO": "12hkO",
        "comp": "12mpi",
        "sup": "1in",
	"manner": "12sti",
        "comp-manner": "12mmin",
        "sup-manner": "1immin",
    },
    "fi-decl-vanhempi": {
    	"nargs": 2,
        "": "1mpi",
        "-poss": "1mp2",
        "gen-sg": "1mm2n",
        "gen-sg-poss": "1mp2",
        "ptv-sg": "1mp22",
        "ine-sg": "1mm2ss2",
        "ela-sg": "1mm2st2",
        "ill-sg": "1mp2@n",
        "ill-sg-poss": "1mp2@",
        "ade-sg": "1mm2ll2",
        "abl-sg": "1mm2lt2",
        "all-sg": "1mm2lle",
        "ess-sg": "1mp2n2",
        "tra-sg": "1mm2ksi",
        "tra-sg-poss": "1mm2kse",
        "ins-sg": None,
        "abe-sg": "1mm2tt2",
        "nom-pl": "1mm2t",
        "nom-pl-poss": "1mp2",
        "gen-pl": ["1mpien", "1mp2in"],
        "gen-pl-poss": ["1mpie", "1mp2i"],
        "ptv-pl": ["1mpi2"],
        "ine-pl": "1mmiss2",
        "ela-pl": "1mmist2",
        "ill-pl": "1mpiin",
        "ill-pl-poss": "1mpii",
        "ade-pl": "1mmill2",
        "abl-pl": "1mmilt2",
        "all-pl": "1mmille",
        "ess-pl": "1mpin2",
        "tra-pl": "1mmiksi",
        "tra-pl-poss": "1mmikse",
        "ins-pl": "1mmin",
        "ins-pl-poss": None,
        "abe-pl": "1mmitt2",
        "cmt": "1mpine",
    },
    "fi-decl-vapaa": {
        # Note: also includes words like "takuu"
    	"nargs": 2,
        "": "1@",
        "gen-sg": "1@n",
        "gen-sg-poss": "1@",
        "ptv-sg": ["1@t2"],
        "ine-sg": "1@ss2",
        "ela-sg": "1@st2",
        "ill-sg": "1@seen",
        "ill-sg-poss": "1@see",
        "ade-sg": "1@ll2",
        "abl-sg": "1@lt2",
        "all-sg": "1@lle",
        "ess-sg": "1@n2",
        "tra-sg": "1@ksi",
        "tra-sg-poss": "1@kse",
        "ins-sg": None,
        "abe-sg": "1@tt2",
        "nom-pl": "1@t",
        "nom-pl-poss": "1@",
        "gen-pl": ["1iden", "1itten"],
        "gen-pl-poss": ["1ide", "1itte"],
        "ptv-pl": ["1it2"],
        "ine-pl": ["1iss2"],
        "ela-pl": ["1ist2"],
        "ill-pl": ["1isiin", "1ihin"],  # Last rare
        "ill-pl-poss": ["1isii", "1ihi"],  # Last rare
        "ade-pl": ["1ill2"],
        "abl-pl": ["1ilt2"],
        "all-pl": ["1ille"],
        "ess-pl": ["1in2"],
        "tra-pl": ["1iksi"],
        "tra-pl-poss": ["1ikse"],
        "ins-pl": ["1in"],
        "ins-pl-poss": None,
        "abe-pl": ["1itt2"],
        "cmt": ["1ine"],
        "hkO": "1@hk2-O",
        "comp": "1@mpi",
        "sup": "1in",
	"manner": "1@sti",
        "comp-manner": "1@mmin",
        "sup-manner": "1immin",
    },
    "fi-decl-maa": {
    	"nargs": 2,
        "": "1",
        "gen-sg": "1n",
        "gen-sg-poss": "1",
        "ptv-sg": ["1t2"],
        "ine-sg": "1ss2",
        "ela-sg": "1st2",
        "ill-sg": "1h@n",
        "ill-sg-poss": "1h@",
        "ade-sg": "1ll2",
        "abl-sg": "1lt2",
        "all-sg": "1lle",
        "ess-sg": "1n2",
        "tra-sg": "1ksi",
        "tra-sg-poss": "1kse",
        "ins-sg": None,
        "abe-sg": "1tt2",
        "nom-pl": "1t",
        "nom-pl-poss": "1",
        "gen-pl": ["1-iden", "1-itten"],
        "gen-pl-poss": ["1-ide", "1-itte"],
        "ptv-pl": ["1-it2"],
        "ine-pl": ["1-iss2"],
        "ela-pl": ["1-ist2"],
        "ill-pl": ["1-ihin"],
        "ill-pl-poss": ["1-ihi"],
        "ade-pl": ["1-ill2"],
        "abl-pl": ["1-ilt2"],
        "all-pl": ["1-ille"],
        "ess-pl": ["1-in2"],
        "tra-pl": ["1-iksi"],
        "tra-pl-poss": ["1-ikse"],
        "ins-pl": ["1-in"],
        "ins-pl-poss": None,
        "abe-pl": ["1-itt2"],
        "cmt": ["1-ine"],
        "hkO": "1hk2-O",
        "comp": "1mpi",
        "sup": "1-in",
	"manner": "1sti",
        "comp-manner": "1mmin",
        "sup-manner": "1-immin",
    },
    "fi-decl-suo": {
    	"nargs": 2,
        "": "1",
        "gen-sg": "1n",
        "gen-sg-poss": "1",
        "ptv-sg": ["1t2"],
        "ine-sg": "1ss2",
        "ela-sg": "1st2",
        "ill-sg": "1h@n",
        "ill-sg-poss": "1h@",
        "ade-sg": "1ll2",
        "abl-sg": "1lt2",
        "all-sg": "1lle",
        "ess-sg": "1n2",
        "tra-sg": "1ksi",
        "tra-sg-poss": "1kse",
        "ins-sg": None,
        "abe-sg": "1tt2",
        "nom-pl": "1t",
        "nom-pl-poss": "1",
        "gen-pl": ["1/iden", "1/itten"],
        "gen-pl-poss": ["1/ide", "1/itte"],
        "ptv-pl": ["1/it2"],
        "ine-pl": ["1/iss2"],
        "ela-pl": ["1/ist2"],
        "ill-pl": ["1/ihin"],
        "ill-pl-poss": ["1/ihi"],
        "ade-pl": ["1/ill2"],
        "abl-pl": ["1/ilt2"],
        "all-pl": ["1/ille"],
        "ess-pl": ["1/in2"],
        "tra-pl": ["1/iksi"],
        "tra-pl-poss": ["1/ikse"],
        "ins-pl": ["1/in"],
        "ins-pl-poss": None,
        "abe-pl": ["1/itt2"],
        "cmt": ["1/ine"],
        "hkO": "1hkO",
        "comp": "1mpi",
        "sup": "1/in",
	"manner": "1sti",
        "comp-manner": "1mmin",
        "sup-manner": "1/immin",
    },
    "fi-decl-rosé": {
    	"nargs": 2,
        "": "1",
        "gen-sg": "1n",
        "gen-sg-poss": "1",
        "ptv-sg": ["1t2"],
        "ine-sg": "1ss2",
        "ela-sg": "1st2",
        "ill-sg": "1h@n",
        "ill-sg-poss": "1h@",
        "ade-sg": "1ll2",
        "abl-sg": "1lt2",
        "all-sg": "1lle",
        "ess-sg": "1n2",
        "tra-sg": "1ksi",
        "tra-sg-poss": "1kse",
        "ins-sg": None,
        "abe-sg": "1tt2",
        "nom-pl": "1t",
        "nom-pl-poss": "1",
        "gen-pl": ["1iden", "1itten"],
        "gen-pl-poss": ["1ide", "1itte"],
        "ptv-pl": ["1it2"],
        "ine-pl": ["1iss2"],
        "ela-pl": ["1ist2"],
        "ill-pl": ["1ihin"],
        "ill-pl-poss": ["1ihi"],
        "ade-pl": ["1ill2"],
        "abl-pl": ["1ilt2"],
        "all-pl": ["1ille"],
        "ess-pl": ["1in2"],
        "tra-pl": ["1iksi"],
        "tra-pl-poss": ["1ikse"],
        "ins-pl": ["1in"],
        "ins-pl-poss": None,
        "abe-pl": ["1itt2"],
        "cmt": ["1ine"],
        "hkO": "1hkO",
        "comp": "1mpi",
        "sup": "1in",
	"manner": "1sti",
        "comp-manner": "1mmin",
        "sup-manner": "1immin",
    },
    "fi-decl-parfait": {
    	"nargs": 2,
        "": "1",
        "-clitic": "1'",
        "-poss": "1'",
        "gen-sg": "1'n",
        "gen-sg-poss": "1'",
        "ptv-sg": ["1't2"],
        "ine-sg": "1'ss2",
        "ela-sg": "1'st2",
        "ill-sg": "1'h@n",
        "ill-sg-poss": "1'h@",
        "ade-sg": "1'll2",
        "abl-sg": "1'lt2",
        "all-sg": "1'lle",
        "ess-sg": "1'n2",
        "tra-sg": "1'ksi",
        "tra-sg-poss": "1'kse",
        "ins-sg": None,
        "abe-sg": "1'tt2",
        "nom-pl": "1't",
        "nom-pl-poss": "1'",
        "gen-pl": ["1'iden", "1'itten"],
        "gen-pl-poss": ["1'ide", "1'itte"],
        "ptv-pl": ["1'it2"],
        "ine-pl": ["1'iss2"],
        "ela-pl": ["1'ist2"],
        "ill-pl": ["1'ihin"],
        "ill-pl-poss": ["1'ihi"],
        "ade-pl": ["1'ill2"],
        "abl-pl": ["1'ilt2"],
        "all-pl": ["1'ille"],
        "ess-pl": ["1'in2"],
        "tra-pl": ["1'iksi"],
        "tra-pl-poss": ["1'ikse"],
        "ins-pl": ["1'in"],
        "ins-pl-poss": None,
        "abe-pl": ["1'itt2"],
        "cmt": ["1'ine"],
        "hkO": "1'hk2-O",
        "comp": "1'mpi",
        "sup": "1'in",
	"manner": "1'sti",
        "comp-manner": "1'mmin",
        "sup-manner": "1'immin",
    },
    "fi-decl-tiili": {
    	"nargs": 2,
        "": "1i",
        "-poss": "1e",
        "gen-sg": "1en",
        "gen-sg-poss": "1e",
        "ptv-sg": "1t2",
        "ine-sg": "1ess2",
        "ela-sg": "1est2",
        "ill-sg": "1een",
        "ill-sg-poss": "1ee",
        "ade-sg": "1ell2",
        "abl-sg": "1elt2",
        "all-sg": "1elle",
        "ess-sg": "1en2",
        "tra-sg": "1eksi",
        "tra-sg-poss": "1ekse",
        "ins-sg": None,
        "abe-sg": "1ett2",
        "nom-pl": "1et",
        "nom-pl-poss": "1e",
        "gen-pl": "1ien",
        "gen-pl-poss": "1ie",
        "ptv-pl": "1i2",
        "ine-pl": "1iss2",
        "ela-pl": "1ist2",
        "ill-pl": "1iin",
        "ill-pl-poss": "1ii",
        "ade-pl": "1ill2",
        "abl-pl": "1ilt2",
        "all-pl": "1ille",
        "ess-pl": "1in2",
        "tra-pl": "1iksi",
        "tra-pl-poss": "1ikse",
        "ins-pl": "1in",
        "ins-pl-poss": None,
        "abe-pl": "1itt2",
        "cmt": "1ine",
        "hkO": "1ehk2-O",
        "comp": "1empi",
        "sup": "1ein",
	"manner": "1esti",
        "comp-manner": "1emmin",
        "sup-manner": "1immin",
    },
    "fi-decl-uni": {
    	"nargs": 2,
        "": "1i",
        "-poss": "1e",
        "gen-sg": "1en",
        "gen-sg-poss": "1e",
        "ptv-sg": "1t2-9",
        "ine-sg": "1ess2",
        "ela-sg": "1est2",
        "ill-sg": "1een",
        "ill-sg-poss": "1ee",
        "ade-sg": "1ell2",
        "abl-sg": "1elt2",
        "all-sg": "1elle",
        "ess-sg": "1en2",
        "tra-sg": "1eksi",
        "tra-sg-poss": "1ekse",
        "ins-sg": None,
        "abe-sg": "1ett2",
        "nom-pl": "1et",
        "nom-pl-poss": "1e",
        "gen-pl": ["1ien", "1ten"],
        "gen-pl-poss": ["1ie", "1te"],
        "ptv-pl": "1i2",
        "ine-pl": "1iss2",
        "ela-pl": "1ist2",
        "ill-pl": "1iin",
        "ill-pl-poss": "1ii",
        "ade-pl": "1ill2",
        "abl-pl": "1ilt2",
        "all-pl": "1ille",
        "ess-pl": "1in2",
        "tra-pl": "1iksi",
        "tra-pl-poss": "1ikse",
        "ins-pl": "1in",
        "ins-pl-poss": None,
        "abe-pl": "1itt2",
        "cmt": "1ine",
        "hkO": "1ehk2-O",
        "comp": "1empi",
        "sup": "1in",
	"manner": "1esti",
        "comp-manner": "1emmin",
        "sup-manner": "1immin",
    },
    "fi-decl-toimi": {
    	"nargs": 2,
        "": "1mi",
        "-poss": "1me",
        "gen-sg": "1men",
        "gen-sg-poss": "1me",
        "ptv-sg": ["1nt2", "1me2"],
        "ine-sg": "1mess2",
        "ela-sg": "1mest2",
        "ill-sg": "1meen",
        "ill-sg-poss": "1mee",
        "ade-sg": "1mell2",
        "abl-sg": "1melt2",
        "all-sg": "1melle",
        "ess-sg": "1men2",
        "tra-sg": "1meksi",
        "tra-sg-poss": "1mekse",
        "ins-sg": None,
        "abe-sg": "1mett2",
        "nom-pl": "1met",
        "nom-pl-poss": "1me",
        "gen-pl": ["1mien", "1nten"],
        "gen-pl-poss": ["1mie", "1nte"],
        "ptv-pl": "1mi2",
        "ine-pl": "1miss2",
        "ela-pl": "1mist2",
        "ill-pl": "1miin",
        "ill-pl-poss": "1mii",
        "ade-pl": "1mill2",
        "abl-pl": "1milt2",
        "all-pl": "1mille",
        "ess-pl": "1min2",
        "tra-pl": "1miksi",
        "tra-pl-poss": "1mikse",
        "ins-pl": "1min",
        "ins-pl-poss": None,
        "abe-pl": "1mitt2",
        "cmt": "1mine",
        "hkO": "1hk2-O",
        "comp": "1mempi",
        "sup": "1min",
	"manner": "1mesti",
        "comp-manner": "1memmin",
        "sup-manner": "1mimmin",
    },
    "fi-decl-pieni": {
    	"nargs": 2,
        "": "1i",
        "-poss": "1e",
        "gen-sg": "1en",
        "gen-sg-poss": "1e",
        "ptv-sg": "1t2-9",
        "ine-sg": "1ess2",
        "ela-sg": "1est2",
        "ill-sg": "1een",
        "ill-sg-poss": "1ee",
        "ade-sg": "1ell2",
        "abl-sg": "1elt2",
        "all-sg": "1elle",
        "ess-sg": "1en2",
        "tra-sg": "1eksi",
        "tra-sg-poss": "1ekse",
        "ins-sg": None,
        "abe-sg": "1ett2",
        "nom-pl": "1et",
        "nom-pl-poss": "1e",
        "gen-pl": ["1ten", "1ien"],
        "gen-pl-poss": ["1te", "1ie"],
        "ptv-pl": "1i2",
        "ine-pl": "1iss2",
        "ela-pl": "1ist2",
        "ill-pl": "1iin",
        "ill-pl-poss": "1ii",
        "ade-pl": "1ill2",
        "abl-pl": "1ilt2",
        "all-pl": "1ille",
        "ess-pl": "1in2",
        "tra-pl": "1iksi",
        "tra-pl-poss": "1ikse",
        "ins-pl": "1in",
        "ins-pl-poss": None,
        "abe-pl": "1itt2",
        "cmt": "1ine",
        "hkO": "1ehk2-O",
        "comp": "1empi",
        "sup": "1in",
	"manner": "1esti",
        "comp-manner": "1emmin",
        "sup-manner": "1immin",
    },
    "fi-decl-käsi": {
    	"nargs": 2,
        "": "1si",
        "-poss": "1te",
        "gen-sg": "1den",
        "gen-sg-poss": "1te",
        "ptv-sg": "1tt2",
        "ine-sg": "1dess2",
        "ela-sg": "1dest2",
        "ill-sg": "1teen",
        "ill-sg-poss": "1tee",
        "ade-sg": "1dell2",
        "abl-sg": "1delt2",
        "all-sg": "1delle",
        "ess-sg": "1ten2",
        "tra-sg": "1deksi",
        "tra-sg-poss": "1dekse",
        "ins-sg": None,
        "abe-sg": "1dett2",
        "nom-pl": "1det",
        "nom-pl-poss": "1te",
        "gen-pl": ["1sien", "1tten"],  # Latter rare
        "gen-pl-poss": ["1sie", "1tte"],  # Latter rare
        "ptv-pl": "1si2",
        "ine-pl": "1siss2",
        "ela-pl": "1sist2",
        "ill-pl": "1siin",
        "ill-pl-poss": "1sii",
        "ade-pl": "1sill2",
        "abl-pl": "1silt2",
        "all-pl": "1sille",
        "ess-pl": "1sin2",
        "tra-pl": "1siksi",
        "tra-pl-poss": "1sikse",
        "ins-pl": "1sin",
        "ins-pl-poss": None,
        "abe-pl": "1sitt2",
        "cmt": "1sine",
        "hkO": "1dehk2-O",
        "comp": "1dempi",
        "sup": "1sin",
	"manner": "1desti",
        "comp-manner": "1demmin",
        "sup-manner": "1simmin",
    },
    "fi-decl-kynsi": {
    	"nargs": 2,
        "": "1si",
        "-poss": "1te",
        "gen-sg": "1nen",
        "gen-sg-poss": "1te",
        "ptv-sg": "1tt2",
        "ine-sg": "1ness2",
        "ela-sg": "1nest2",
        "ill-sg": "1teen",
        "ill-sg-poss": "1tee",
        "ade-sg": "1nell2",
        "abl-sg": "1nelt2",
        "all-sg": "1nelle",
        "ess-sg": "1ten2",
        "tra-sg": "1neksi",
        "tra-sg-poss": "1nekse",
        "ins-sg": None,
        "abe-sg": "1nett2",
        "nom-pl": "1net",
        "nom-pl-poss": "1te",
        "gen-pl": ["1sien", "1tten"],  # Latter rare
        "gen-pl-poss": ["1sie", "1tte"],  # Latter rare
        "ptv-pl": "1si2",
        "ine-pl": "1siss2",
        "ela-pl": "1sist2",
        "ill-pl": "1siin",
        "ill-pl-poss": "1sii",
        "ade-pl": "1sill2",
        "abl-pl": "1silt2",
        "all-pl": "1sille",
        "ess-pl": "1sin2",
        "tra-pl": "1siksi",
        "tra-pl-poss": "1sikse",
        "ins-pl": "1sin",
        "ins-pl-poss": None,
        "abe-pl": "1sitt2",
        "cmt": "1sine",
        "hkO": "1nehk2-O",
        "comp": "1nempi",
        "sup": "1sin",
	"manner": "1nesti",
        "comp-manner": "1nemmin",
        "sup-manner": "1simmin",
    },
    "fi-decl-lapsi": {
    	"nargs": 2,
        "": "1si",
        "-poss": "1se",
        "gen-sg": "1sen",
        "gen-sg-poss": "1se",
        "ptv-sg": "1-st2",
        "ine-sg": "1sess2",
        "ela-sg": "1sest2",
        "ill-sg": "1seen",
        "ill-sg-poss": "1see",
        "ade-sg": "1sell2",
        "abl-sg": "1selt2",
        "all-sg": "1selle",
        "ess-sg": "1sen2",
        "tra-sg": "1seksi",
        "tra-sg-poss": "1sekse",
        "ins-sg": None,
        "abe-sg": "1sett2",
        "nom-pl": "1set",
        "nom-pl-poss": "1se",
        "gen-pl": ["1sien", "1-sten"],
        "gen-pl-poss": ["1sie", "1-ste"],
        "ptv-pl": "1si2",
        "ine-pl": "1siss2",
        "ela-pl": "1sist2",
        "ill-pl": "1siin",
        "ill-pl-poss": "1sii",
        "ade-pl": "1sill2",
        "abl-pl": "1silt2",
        "all-pl": "1sille",
        "ess-pl": "1sin2",
        "tra-pl": "1siksi",
        "tra-pl-poss": "1sikse",
        "ins-pl": "1sin",
        "ins-pl-poss": None,
        "abe-pl": "1sitt2",
        "cmt": "1sine",
        "hkO": "1sehk2-O",
        "comp": "1sempi",
        "sup": "1sin",
	"manner": "1sesti",
        "comp-manner": "1semmin",
        "sup-manner": "1simmin",
    },
    "fi-decl-veitsi": {
    	"nargs": 2,
        "": "1tsi",
        "-poss": "1tse",
        "gen-sg": "1tsen",
        "gen-sg-poss": "1tse",
        "ptv-sg": "1st2",
        "ine-sg": "1tsess2",
        "ela-sg": "1tsest2",
        "ill-sg": "1tseen",
        "ill-sg-poss": "1tsee",
        "ade-sg": "1tsell2",
        "abl-sg": "1tselt2",
        "all-sg": "1tselle",
        "ess-sg": "1tsen2",
        "tra-sg": "1tseksi",
        "tra-sg-poss": "1tsekse",
        "ins-sg": None,
        "abe-sg": "1tsett2",
        "nom-pl": "1tset",
        "nom-pl-poss": "1tse",
        "gen-pl": ["1tsien", "1sten"],
        "gen-pl-poss": ["1tsie", "1ste"],
        "ptv-pl": "1tsi2",
        "ine-pl": "1tsiss2",
        "ela-pl": "1tsist2",
        "ill-pl": "1tsiin",
        "ill-pl-poss": "1tsii",
        "ade-pl": "1tsill2",
        "abl-pl": "1tsilt2",
        "all-pl": "1tsille",
        "ess-pl": "1tsin2",
        "tra-pl": "1tsiksi",
        "tra-pl-poss": "1tsikse",
        "ins-pl": "1tsin",
        "ins-pl-poss": None,
        "abe-pl": "1tsitt2",
        "cmt": "1tsine",
        "hkO": "1tsehk2-O",
        "comp": "1tsempi",
        "sup": "1tsin",
	"manner": "1tsesti",
        "comp-manner": "1tsemmin",
        "sup-manner": "1tsimmin",
    },
    "fi-decl-kaksi": {
    	"nargs": 2,
        "": "1ksi",
        "-poss": "1hte",
        "gen-sg": "1hden",
        "gen-sg-poss": "1hte",
        "ptv-sg": "1ht2",
        "ine-sg": "1hdess2",
        "ela-sg": "1hdest2",
        "ill-sg": "1hteen",
        "ill-sg-poss": "1htee",
        "ade-sg": "1hdell2",
        "abl-sg": "1hdelt2",
        "all-sg": "1hdelle",
        "ess-sg": "1hten2",
        "tra-sg": "1hdeksi",
        "tra-sg-poss": "1hdekse",
        "ins-sg": None,
        "abe-sg": "1hdett2",
        "nom-pl": "1hdet",
        "nom-pl-poss": "1hte",
        "gen-pl": ["1ksien"],
        "gen-pl-poss": ["1ksie"],
        "ptv-pl": "1ksi2",
        "ine-pl": "1ksiss2",
        "ela-pl": "1ksist2",
        "ill-pl": "1ksiin",
        "ill-pl-poss": "1ksii",
        "ade-pl": "1ksill2",
        "abl-pl": "1ksilt2",
        "all-pl": "1ksille",
        "ess-pl": "1ksin2",
        "tra-pl": "1ksiksi",
        "tra-pl-poss": "1ksikse",
        "ins-pl": "1ksin",
        "ins-pl-poss": None,
        "abe-pl": "1ksitt2",
        "cmt": "1ksine",
        "hkO": "1hdehk2-O",
        "comp": "1hdempi",
        "sup": "1ksin",
	"manner": "1hdesti",
        "comp-manner": "1hdemmin",
        "sup-manner": "1ksimmin",
    },
    "fi-decl-sisar": {
    	"nargs": 5,
        "": "124",
        "-poss": "134e",
        "gen-sg": "134en",
        "gen-sg-poss": "134e",
        "ptv-sg": "124t5",
        "ine-sg": "134ess5",
        "ela-sg": "134est5",
        "ill-sg": "134een",
        "ill-sg-poss": "134ee",
        "ade-sg": "134ell5",
        "abl-sg": "134elt5",
        "all-sg": "134elle",
        "ess-sg": "134en5",
        "tra-sg": "134eksi",
        "tra-sg-poss": "134ekse",
        "ins-sg": None,
        "abe-sg": "134ett5",
        "nom-pl": "134et",
        "nom-pl-poss": "134e",
        "gen-pl": ["134ien", "124ten"],
        "gen-pl-poss": ["134ie", "124te"],
        "ptv-pl": "134i5",
        "ine-pl": "134iss5",
        "ela-pl": "134ist5",
        "ill-pl": "134iin",
        "ill-pl-poss": "134ii",
        "ade-pl": "134ill5",
        "abl-pl": "134ilt5",
        "all-pl": "134ille",
        "ess-pl": "134in5",
        "tra-pl": "134iksi",
        "tra-pl-poss": "134ikse",
        "ins-pl": "134in",
        "ins-pl-poss": None,
        "abe-pl": "134itt5",
        "cmt": "134ine",
        "hkO": "134ehk5-O",
        "comp": "134empi",
        "sup": "134in",
	"manner": "134esti",
        "comp-manner": "134emmin",
        "sup-manner": "134immin",
    },
    "fi-decl-kytkin": {
    	"nargs": 5,
	"default": {"4": "i"},
        "": "124n",
        "-poss": "134me",
        "gen-sg": "134men",
        "gen-sg-poss": "134me",
        "ptv-sg": "124nt5",
        "ine-sg": "134mess5",
        "ela-sg": "134mest5",
        "ill-sg": "134meen",
        "ill-sg-poss": "134mee",
        "ade-sg": "134mell5",
        "abl-sg": "134melt5",
        "all-sg": "134melle",
        "ess-sg": "134men5",
        "tra-sg": "134meksi",
        "tra-sg-poss": "134mekse",
        "ins-sg": None,
        "abe-sg": "134mett5",
        "nom-pl": "134met",
        "nom-pl-poss": "134me",
        "gen-pl": ["134mien", "124nten"],
        "gen-pl-poss": ["134mie", "124nte"],
        "ptv-pl": "134mi5",
        "ine-pl": "134miss5",
        "ela-pl": "134mist5",
        "ill-pl": "134miin",
        "ill-pl-poss": "134mii",
        "ade-pl": "134mill5",
        "abl-pl": "134milt5",
        "all-pl": "134mille",
        "ess-pl": "134min5",
        "tra-pl": "134miksi",
        "tra-pl-poss": "134mikse",
        "ins-pl": "134min",
        "ins-pl-poss": None,
        "abe-pl": "134mitt5",
        "cmt": "134mine",
        "hkO": "134mehk5-O",
        "comp": "134mempi",
        "sup": "134min",
	"manner": "134mesti",
        "comp-manner": "134memmin",
        "sup-manner": "134mimmin",
    },
    "fi-decl-onneton": {
    	"nargs": 2,
        "": "12-tOn",
        "-poss": "12-ttOm2",
        "gen-sg": "12-ttOm2n",
        "gen-sg-poss": "12-ttOm2",
        "ptv-sg": "12-tOnt2",
        "ine-sg": "12-ttOm2ss2",
        "ela-sg": "12-ttOm2st2",
        "ill-sg": "12-ttOm2@n",
        "ill-sg-poss": "12-ttOm2@",
        "ade-sg": "12-ttOm2ll2",
        "abl-sg": "12-ttOm2lt2",
        "all-sg": "12-ttOm2lle",
        "ess-sg": "12-ttOm2n2",
        "tra-sg": "12-ttOm2ksi",
        "tra-sg-poss": "12-ttOm2kse",
        "ins-sg": None,
        "abe-sg": "12-ttOm2tt2",
        "nom-pl": "12-ttOm2t",
        "nom-pl-poss": "12-ttOm2",
        "gen-pl": ["12-ttOmien", "12-tOnten"],  # Latter rare
        "gen-pl-poss": ["12-ttOmie", "12-tOnte"],  # Latter rare
        "ptv-pl": "12-ttOmi2",
        "ine-pl": "12-ttOmiss2",
        "ela-pl": "12-ttOmist2",
        "ill-pl": "12-ttOmiin",
        "ill-pl-poss": "12-ttOmii",
        "ade-pl": "12-ttOmill2",
        "abl-pl": "12-ttOmilt2",
        "all-pl": "12-ttOmille",
        "ess-pl": "12-ttOmin2",
        "tra-pl": "12-ttOmiksi",
        "tra-pl-poss": "12-ttOmikse",
        "ins-pl": "12-ttOmin",
        "ins-pl-poss": None,
        "abe-pl": "12-ttOmitt2",
        "cmt": "12-ttOmine",
        "hkO": "12-ttOm2hkO",
        "comp": "12-ttOm2mpi",
        "sup": "12-ttOmin",
	"manner": "12-ttOm2sti",
        "comp-manner": "12-ttOm2mmin",
        "sup-manner": "12-ttOmimmin",
    },
    "fi-decl-lämmin": {
    	"nargs": 0,
        "": "1lämmin",
        "-poss": "1lämpimä",
        "gen-sg": "1lämpimän",
        "gen-sg-poss": "1lämpimä",
        "ptv-sg": "1lämmintä",
        "ine-sg": "1lämpimässä",
        "ela-sg": "1lämpimästä",
        "ill-sg": "1lämpimään",
        "ill-sg-poss": "1lämpimää",
        "ade-sg": "1lämpimällä",
        "abl-sg": "1lämpimältä",
        "all-sg": "1lämpimälle",
        "ess-sg": "1lämpimänä",
        "tra-sg": "1lämpimäksi",
        "tra-sg-poss": "1lämpimäkse",
        "ins-sg": None,
        "abe-sg": "1lämpimättä",
        "nom-pl": "1lämpimät",
        "nom-pl-poss": "1lämpimä",
        "gen-pl": ["1lämpimien", "1lämminten"],
        "gen-pl-poss": ["1lämpimie", "1lämminte"],
        "ptv-pl": "1lämpimiä",
        "ine-pl": "1lämpimissä",
        "ela-pl": "1lämpimistä",
        "ill-pl": "1lämpimiin",
        "ill-pl-poss": "1lämpimii",
        "ade-pl": "1lämpimillä",
        "abl-pl": "1lämpimiltä",
        "all-pl": "1lämpimille",
        "ess-pl": "1lämpiminä",
        "tra-pl": "1lämpimiksi",
        "tra-pl-poss": "1lämpimikse",
        "ins-pl": "1lämpimin",
        "ins-pl-poss": None,
        "abe-pl": "1lämpimittä",
        "cmt": "1lämpimine",
        "hkO": "1lämpimähkO",
        "comp": "1lämpimämpi",
        "sup": "1lämpimin",
	"manner": "1lämpimästi",
        "comp-manner": "1lämpimämmin",
        "sup-manner": "1lämpimimmin",
    },
    "fi-decl-sisin": {
    	"nargs": 2,
        "": "1in",
        "-poss": "1imp2",
        "gen-sg": "1imm2n",
        "gen-sg-poss": "1imp2",
        "ptv-sg": "1int2",
        "ine-sg": "1imm2ss2",
        "ela-sg": "1imm2st2",
        "ill-sg": "1imp2@n",
        "ill-sg-poss": "1imp2@",
        "ade-sg": "1imm2ll2",
        "abl-sg": "1imm2lt2",
        "all-sg": "1imm2lle",
        "ess-sg": "1imp2n2",
        "tra-sg": "1imm2ksi",
        "tra-sg-poss": "1imm2kse",
        "ins-sg": None,
        "abe-sg": "1imm2tt2",
        "nom-pl": "1imm2t",
        "nom-pl-poss": "1imp2",
        "gen-pl": ["1impien", "1inten"],
        "gen-pl-poss": ["1impie", "1inte"],
        "ptv-pl": ["1impi2"],
        "ine-pl": "1immiss2",
        "ela-pl": "1immist2",
        "ill-pl": "1impiin",
        "ill-pl-poss": "1impii",
        "ade-pl": "1immill2",
        "abl-pl": "1immilt2",
        "all-pl": "1immille",
        "ess-pl": "1impin2",
        "tra-pl": "1immiksi",
        "tra-pl-poss": "1immikse",
        "ins-pl": "1immin",
        "ins-pl-poss": None,
        "abe-pl": "1immitt2",
        "cmt": "1impine",
    },
    "fi-decl-vasen": {
    	"nargs": 0,
        "": "1vasen",
        "-poss": "1vasempa",
        "gen-sg": "1vasemman",
        "gen-sg-poss": "1vasempa",
        "ptv-sg": ["1vasenta", "vasempaa"],
        "ine-sg": "1vasemmassa",
        "ela-sg": "1vasemmasta",
        "ill-sg": "1vasempaan",
        "ill-sg-poss": "1vasempaa",
        "ade-sg": "1vasemmalla",
        "abl-sg": "1vasemmalta",
        "all-sg": "1vasemmalle",
        "ess-sg": "1vasempana",
        "tra-sg": "1vasemmaksi",
        "tra-sg-poss": "1vasemmakse",
        "ins-sg": None,
        "abe-sg": "1vasemmatta",
        "nom-pl": "1vasemmat",
        "nom-pl-poss": "1vasempa",
        "gen-pl": ["1vasempien", "1vasenten", "vasempain"],  # Last rare
        "gen-pl-poss": ["1vasempie", "1vasente", "vasempai"],  # Last rare
        "ptv-pl": "1vasempia",
        "ine-pl": "1vasemmissa",
        "ela-pl": "1vasemmista",
        "ill-pl": "1vasempiin",
        "ill-pl-poss": "1vasempii",
        "ade-pl": "1vasemmilla",
        "abl-pl": "1vasemmilta",
        "all-pl": "1vasemmille",
        "ess-pl": "1vasempina",
        "tra-pl": "1vasemmiksi",
        "tra-pl-poss": "1vasemmikse",
        "ins-pl": "1vasemmin",
        "ins-pl-poss": None,
        "abe-pl": "1vasemmitta",
        "cmt": "1vasempine",
        "comp": ["1vasempi", "1vasemmanpuoleisempi"],
        "sup": "1vasemmanpuoleisin",
	"manner": "1vasemmanpuoleisesti",
        "comp-manner": "1vasemmanpuoleisemmin",
        "sup-manner": "1vasemmanpuoleisimmin",
    },
    "fi-decl-nainen": {
    	"nargs": 2,
        "": "1nen",
        "-poss": "1se",
        "gen-sg": "1sen",
        "gen-sg-poss": "1se",
        "ptv-sg": "1st2",
        "ine-sg": "1sess2",
        "ela-sg": "1sest2",
        "ill-sg": "1seen",
        "ill-sg-poss": "1see",
        "ade-sg": "1sell2",
        "abl-sg": "1selt2",
        "all-sg": "1selle",
        "ess-sg": "1sen2",
        "tra-sg": "1seksi",
        "tra-sg-poss": "1sekse",
        "ins-sg": None,
        "abe-sg": "1sett2",
        "nom-pl": "1set",
        "nom-pl-poss": "1se",
        "gen-pl": ["1sten", "1sien"],
        "gen-pl-poss": ["1ste", "1sie"],
        "ptv-pl": "1si2",
        "ine-pl": "1siss2",
        "ela-pl": "1sist2",
        "ill-pl": "1siin",
        "ill-pl-poss": "1sii",
        "ade-pl": "1sill2",
        "abl-pl": "1silt2",
        "all-pl": "1sille",
        "ess-pl": "1sin2",
        "tra-pl": "1siksi",
        "tra-pl-poss": "1sikse",
        "ins-pl": "1sin",
        "ins-pl-poss": None,
        "abe-pl": "1sitt2",
        "cmt": "1sine",
        "hkO": "1sehko",
        "comp": "1sempi",
        "sup": "1sin",
	"manner": "1sesti",
        "comp-manner": "1semmin",
        "sup-manner": "1simmin",
    },
    "fi-decl-vastaus": {
    	"nargs": 2,
        "": "1s",
        "-poss": "1kse",
        "gen-sg": "1ksen",
        "gen-sg-poss": "1kse",
        "ptv-sg": "1st2",
        "ine-sg": "1ksess2",
        "ela-sg": "1ksest2",
        "ill-sg": "1kseen",
        "ill-sg-poss": "1ksee",
        "ade-sg": "1ksell2",
        "abl-sg": "1kselt2",
        "all-sg": "1kselle",
        "ess-sg": "1ksen2",
        "tra-sg": "1kseksi",
        "tra-sg-poss": "1ksekse",
        "ins-sg": None,
        "abe-sg": "1ksett2",
        "nom-pl": "1kset",
        "nom-pl-poss": "1kse",
        "gen-pl": ["1sten", "1ksien"],
        "gen-pl-poss": ["1ste", "1ksie"],
        "ptv-pl": "1ksi2",
        "ine-pl": "1ksiss2",
        "ela-pl": "1ksist2",
        "ill-pl": "1ksiin",
        "ill-pl-poss": "1ksii",
        "ade-pl": "1ksill2",
        "abl-pl": "1ksilt2",
        "all-pl": "1ksille",
        "ess-pl": "1ksin2",
        "tra-pl": "1ksiksi",
        "tra-pl-poss": "1ksikse",
        "ins-pl": "1ksin",
        "ins-pl-poss": None,
        "abe-pl": "1ksitt2",
        "cmt": "1ksine",
        "hkO": "1ksehk2-O",
        "comp": "1ksempi",
        "sup": "1ksin",
	"manner": "1ksesti",
        "comp-manner": "1ksemmin",
        "sup-manner": "1ksimmin",
    },
    "fi-decl-kalleus": {
    	"nargs": 2,
        "": "1s",
        "-poss": "1te",
        "gen-sg": "1den",
        "gen-sg-poss": "1te",
        "ptv-sg": "1tt2",
        "ine-sg": "1dess2",
        "ela-sg": "1dest2",
        "ill-sg": "1teen",
        "ill-sg-poss": "1tee",
        "ade-sg": "1dell2",
        "abl-sg": "1delt2",
        "all-sg": "1delle",
        "ess-sg": "1ten2",
        "tra-sg": "1deksi",
        "tra-sg-poss": "1dekse",
        "ins-sg": None,
        "abe-sg": "1dett2",
        "nom-pl": "1det",
        "nom-pl-poss": "1te",
        "gen-pl": ["1ksien"],
        "gen-pl-poss": ["1ksie"],
        "ptv-pl": "1ksi2",
        "ine-pl": "1ksiss2",
        "ela-pl": "1ksist2",
        "ill-pl": "1ksiin",
        "ill-pl-poss": "1ksii",
        "ade-pl": "1ksill2",
        "abl-pl": "1ksilt2",
        "all-pl": "1ksille",
        "ess-pl": "1ksin2",
        "tra-pl": "1ksiksi",
        "tra-pl-poss": "1ksikse",
        "ins-pl": "1ksin",
        "ins-pl-poss": None,
        "abe-pl": "1ksitt2",
        "cmt": "1ksine",
        "hkO": "1dehk2-O",
        "comp": "1dempi",
        "sup": "1ksin",
	"manner": "1desti",
        "comp-manner": "1demmin",
        "sup-manner": "1ksimmin",
    },
    "fi-decl-vieras": {
    	"nargs": 5,
	"default": {"4": "a"},
        "": "124s",
        "-poss": "134@",
        "gen-sg": "134@n",
        "gen-sg-poss": "134@",
        "ptv-sg": "124st5",
        "ine-sg": "134@ss5",
        "ela-sg": "134@st5",
        "ill-sg": "134@seen",
        "ill-sg-poss": "134@see",
        "ade-sg": "134@ll5",
        "abl-sg": "134@lt5",
        "all-sg": "134@lle",
        "ess-sg": "134@n5",
        "tra-sg": "134@ksi",
        "tra-sg-poss": "134@kse",
        "ins-sg": None,
        "abe-sg": "134@tt5",
        "nom-pl": "134@t",
        "nom-pl-poss": "134@",
        "gen-pl": ["134iden", "134itten"],
        "gen-pl-poss": ["134ide", "134itte"],
        "ptv-pl": "134it5",
        "ine-pl": "134iss5",
        "ela-pl": "134ist5",
        "ill-pl": ["134isiin", "134ihin"],  # Latter rare
        "ill-pl-poss": ["134isii", "134ihi"],  # Latter rare
        "ade-pl": "134ill5",
        "abl-pl": "134ilt5",
        "all-pl": "134ille",
        "ess-pl": "134in5",
        "tra-pl": "134iksi",
        "tra-pl-poss": "134ikse",
        "ins-pl": "134in",
        "ins-pl-poss": None,
        "abe-pl": "134itt5",
        "cmt": "134ine",
        "hkO": "134@hk5-O",
        "comp": "134@mpi",
        "sup": "134in",
	"manner": "134@sti",
        "comp-manner": "134@mmin",
        "sup-manner": "134immin",
    },
    "fi-decl-mies": {
    	"nargs": 1,
        "": "1mies",
        "-poss": "1miehe",
        "gen-sg": "1miehen",
        "gen-sg-poss": "1miehe",
        "ptv-sg": "1miestä",
        "ine-sg": "1miehessä",
        "ela-sg": "1miehestä",
        "ill-sg": "1mieheen",
        "ill-sg-poss": "1miehee",
        "ade-sg": "1miehellä",
        "abl-sg": "1mieheltä",
        "all-sg": "1miehelle",
        "ess-sg": "1miehenä",
        "tra-sg": "1mieheksi",
        "tra-sg-poss": "1miehekse",
        "ins-sg": None,
        "abe-sg": "1miehettä",
        "nom-pl": "1miehet",
        "nom-pl-poss": "1miehe",
        "gen-pl": ["1miesten", "1miehien"],
        "gen-pl-poss": ["1mieste", "1miehie"],
        "ptv-pl": "1miehiä",
        "ine-pl": "1miehissä",
        "ela-pl": "1miehistä",
        "ill-pl": "1miehiin",
        "ill-pl-poss": "1miehii",
        "ade-pl": "1miehillä",
        "abl-pl": "1miehiltä",
        "all-pl": "1miehille",
        "ess-pl": "1miehinä",
        "tra-pl": "1miehiksi",
        "tra-pl-poss": "1miehikse",
        "ins-pl": "1miehin",
        "ins-pl-poss": None,
        "abe-pl": "1miehittä",
        "cmt": "1miehine",
        "hkO": "1miehehkö",
        "comp": "1miehempi",
        "sup": "1miehin",
	"manner": "1miehesti",
        "comp-manner": "1miehemmin",
        "sup-manner": "1miehimmin",
    },
    "fi-decl-ohut": {
    	"nargs": 5,
	"default": {"4": "u"},
        "": "124t",
        "-poss": "134e",
        "gen-sg": "134en",
        "gen-sg-poss": "134e",
        "ptv-sg": "124tt5",
        "ine-sg": "134ess5",
        "ela-sg": "134est5",
        "ill-sg": "134een",
        "ill-sg-poss": "134ee",
        "ade-sg": "134ell5",
        "abl-sg": "134elt5",
        "all-sg": "134elle",
        "ess-sg": "134en5",
        "tra-sg": "134eksi",
        "tra-sg-poss": "134ekse",
        "ins-sg": None,
        "abe-sg": "134ett5",
        "nom-pl": "134et",
        "nom-pl-poss": "134e",
        "gen-pl": ["134iden", "134itten"],
        "gen-pl-poss": ["134ide", "134itte"],
        "ptv-pl": "134it5",
        "ine-pl": "134iss5",
        "ela-pl": "134ist5",
        "ill-pl": ["134isiin", "134ihin"],
        "ill-pl-poss": ["134isii", "134ihi"],
        "ade-pl": "134ill5",
        "abl-pl": "134ilt5",
        "all-pl": "134ille",
        "ess-pl": "134in5",
        "tra-pl": "134iksi",
        "tra-pl-poss": "134ikse",
        "ins-pl": "134in",
        "ins-pl-poss": None,
        "abe-pl": "134itt5",
        "cmt": "134ine",
        "hkO": "134ehk5-O",
        "comp": "134empi",
        "sup": "134in",
	"manner": "134esti",
        "comp-manner": "134emmin",
        "sup-manner": "134immin",
    },
    "fi-decl-kevät": {
    	"nargs": 2,
        "": "1t",
        "-poss": "12",
        "gen-sg": "12n",
        "gen-sg-poss": "12",
        "ptv-sg": ["1tt2"],
        "ine-sg": "12ss2",
        "ela-sg": "12st2",
        "ill-sg": "12seen",
        "ill-sg-poss": "12see",
        "ade-sg": "12ll2",
        "abl-sg": "12lt2",
        "all-sg": "12lle",
        "ess-sg": "12n2",
        "tra-sg": "12ksi",
        "tra-sg-poss": "12kse",
        "ins-sg": None,
        "abe-sg": "12tt2",
        "nom-pl": "1t",
        "nom-pl-poss": "12",
        "gen-pl": ["1iden", "1itten"],
        "gen-pl-poss": ["1ide", "1itte"],
        "ptv-pl": ["1it2"],
        "ine-pl": ["1iss2"],
        "ela-pl": ["1ist2"],
        "ill-pl": ["1isiin", "1ihin"],  # Last rare
        "ill-pl-poss": ["1isii", "1ihi"],  # Last rare
        "ade-pl": ["1ill2"],
        "abl-pl": ["1ilt2"],
        "all-pl": ["1ille"],
        "ess-pl": ["1in2"],
        "tra-pl": ["1iksi"],
        "tra-pl-poss": ["1ikse"],
        "ins-pl": ["1in"],
        "ins-pl-poss": None,
        "abe-pl": ["1itt2"],
        "cmt": ["1ine"],
        "hkO": "12hkO",
        "comp": "12mpi",
        "sup": "1in",
	"manner": "12sti",
        "comp-manner": "12mmin",
        "sup-manner": "1immin",
    },
    "fi-decl-kahdeksas": {
    	"nargs": 2,
        "": "1s",
        "-poss": "1nte",
        "gen-sg": "1nnen",
        "gen-sg-poss": "1nte",
        "ptv-sg": "1tt2",
        "ine-sg": "1nness2",
        "ela-sg": "1nnest2",
        "ill-sg": "1nteen",
        "ill-sg-poss": "1ntee",
        "ade-sg": "1nnell2",
        "abl-sg": "1nnelt2",
        "all-sg": "1nnelle",
        "ess-sg": "1nten2",
        "tra-sg": "1nneksi",
        "tra-sg-poss": "1nnekse",
        "ins-sg": None,
        "abe-sg": "1nnett2",
        "nom-pl": "1nnet",
        "nom-pl-poss": "1nte",
        "gen-pl": ["1nsien"],
        "gen-pl-poss": ["1nsie"],
        "ptv-pl": "1nsi2",
        "ine-pl": "1nsiss2",
        "ela-pl": "1nsist2",
        "ill-pl": "1nsiin",
        "ill-pl-poss": "1nsii",
        "ade-pl": "1nsill2",
        "abl-pl": "1nsilt2",
        "all-pl": "1nsille",
        "ess-pl": "1nsin2",
        "tra-pl": "1nsiksi",
        "tra-pl-poss": "1nsikse",
        "ins-pl": "1nsin",
        "ins-pl-poss": None,
        "abe-pl": "1nsitt2",
        "cmt": "1nsine",
        "hkO": "1hk2-O",
        "comp": "1mpi",
        "sup": "1-in",
	"manner": "1nnesti",
        "comp-manner": "1nnemmin",
        "sup-manner": "1nsimmin",
    },
    "fi-decl-tuhat": {
    	"nargs": 2,
        "": "1t",
        "-poss": "1nte",
        "gen-sg": "1nnen",
        "gen-sg-poss": "1nte",
        "ptv-sg": "1tt2",
        "ine-sg": "1nness2",
        "ela-sg": "1nnest2",
        "ill-sg": "1nteen",
        "ill-sg-poss": "1ntee",
        "ade-sg": "1nnell2",
        "abl-sg": "1nnelt2",
        "all-sg": "1nnelle",
        "ess-sg": "1nten2",
        "tra-sg": "1nneksi",
        "tra-sg-poss": "1nnekse",
        "ins-sg": None,
        "abe-sg": "1nnett2",
        "nom-pl": "1nnet",
        "nom-pl-poss": "1nte",
        "gen-pl": ["1nsien", "1nten"],  # Latter rare
        "gen-pl-poss": ["1nsie", "1nte"],  # Latter rare
        "ptv-pl": "1nsi2",
        "ine-pl": "1nsiss2",
        "ela-pl": "1nsist2",
        "ill-pl": "1nsiin",
        "ill-pl-poss": "1nsii",
        "ade-pl": "1nsill2",
        "abl-pl": "1nsilt2",
        "all-pl": "1nsille",
        "ess-pl": "1nsin2",
        "tra-pl": "1nsiksi",
        "tra-pl-poss": "1nsikse",
        "ins-pl": "1nsin",
        "ins-pl-poss": None,
        "abe-pl": "1nsitt2",
        "cmt": "1nsine",
        "hkO": "1nnehk2-O",
        "comp": "1nnempi",
        "sup": "1nsin",
	"manner": "1nnesti",
        "comp-manner": "1nnemmin",
        "sup-manner": "1nsimmin",
    },
    "fi-decl-kuollut": {
    	"nargs": 2,
        "": "12-Ut",
        "-poss": "1ee",
        "gen-sg": "1een",
        "gen-sg-poss": "1ee",
        "ptv-sg": "12-Utt2",
        "ine-sg": "1eess2",
        "ela-sg": "1eest2",
        "ill-sg": "1eeseen",
        "ill-sg-poss": "1eesee",
        "ade-sg": "1eell2",
        "abl-sg": "1eelt2",
        "all-sg": "1eelle",
        "ess-sg": "1een2",
        "tra-sg": "1eeksi",
        "tra-sg-poss": "1eekse",
        "ins-sg": None,
        "abe-sg": "1eett2",
        "nom-pl": "1eet",
        "nom-pl-poss": "1ee",
        "gen-pl": ["1eiden", "1eitten"],  # Latter rare
        "gen-pl-poss": ["1eide", "1eitte"],  # Latter rare
        "ptv-pl": "1eit2",
        "ine-pl": "1eiss2",
        "ela-pl": "1eist2",
        "ill-pl": ["1eisiin", "1eihin"],
        "ill-pl-poss": ["1eisii", "1eihi"],
        "ade-pl": "1eill2",
        "abl-pl": "1eilt2",
        "all-pl": "1eille",
        "ess-pl": "1ein2",
        "tra-pl": "1eiksi",
        "tra-pl-poss": "1eikse",
        "ins-pl": "1ein",
        "ins-pl-poss": None,
        "abe-pl": "1eitt2",
        "cmt": "1eine",
        "hkO": "1eehk2-O",
        "comp": "1eempi",
        "sup": "1ein",
	"manner": "1eesti",
        "comp-manner": "1eemmin",
        "sup-manner": "1eimmin",
    },
    "fi-decl-hame": {
    	"nargs": 4,
        "": "12e",
        "-poss": "13ee",
        "gen-sg": "13een",
        "gen-sg-poss": "13ee",
        "ptv-sg": "12ett4",
        "ine-sg": "13eess4",
        "ela-sg": "13eest4",
        "ill-sg": "13eeseen",
        "ill-sg-poss": "13eesee",
        "ade-sg": "13eell4",
        "abl-sg": "13eelt4",
        "all-sg": "13eelle",
        "ess-sg": "13een4",
        "tra-sg": "13eeksi",
        "tra-sg-poss": "13eekse",
        "ins-sg": None,
        "abe-sg": "13eett4",
        "nom-pl": "13eet",
        "nom-pl-poss": "13ee",
        "gen-pl": ["13eiden", "13eitten"],
        "gen-pl-poss": ["13eide", "13eitte"],
        "ptv-pl": "13eit4",
        "ine-pl": "13eiss4",
        "ela-pl": "13eist4",
        "ill-pl": ["13eisiin", "13eihin"],
        "ill-pl-poss": ["13eisii", "13eihi"],
        "ade-pl": "13eill4",
        "abl-pl": "13eilt4",
        "all-pl": "13eille",
        "ess-pl": "13ein4",
        "tra-pl": "13eiksi",
        "tra-pl-poss": "13eikse",
        "ins-pl": "13ein",
        "ins-pl-poss": None,
        "abe-pl": "13eitt4",
        "cmt": "13eine",
        "hkO": "13eehk4-O",
        "comp": "13eempi",
        "sup": "13ein",
	"manner": "13eesti",
        "comp-manner": "13eemmin",
        "sup-manner": "13eimmin",
    },

    "fi-decl-askel": {
    	"nargs": 5,
        "": ["124", "134e"],
        "-poss": ["134e", "134ee"],
        "gen-sg": ["134en", "134een"],
        "gen-sg-poss": ["134e", "134ee"],
        "ptv-sg": ["124t5", "134ett5"],
        "ine-sg": ["134ess5", "134eess5"],
        "ela-sg": ["134est5", "134eest5"],
        "ill-sg": ["134een", "134eeseen"],
        "ill-sg-poss": ["134ee", "134eesee"],
        "ade-sg": ["134ell5", "134eell5"],
        "abl-sg": ["134elt5", "134eelt5"],
        "all-sg": ["134elle", "134eelle"],
        "ess-sg": ["134en5", "134een5"],
        "tra-sg": ["134eksi", "134eeksi"],
        "tra-sg-poss": ["134ekse", "134eekse"],
        "ins-sg": None,
        "abe-sg": ["134ett5", "134eett5"],
        "nom-pl": ["134et", "134eet"],
        "nom-pl-poss": ["134e", "134ee"],
        "gen-pl": ["134ien", "124ten", "134eiden", "134eitten"],
        "gen-pl-poss": ["134ie", "124te", "134eide", "134eitte"],
        "ptv-pl": ["134i5", "134eit5"],
        "ine-pl": ["134iss5", "134eiss5"],
        "ela-pl": ["134ist5", "134eist5"],
        "ill-pl": ["134iin", "134eisiin"],
        "ill-pl-poss": ["134ii", "134eisii"],
        "ade-pl": ["134ill5", "134eill5"],
        "abl-pl": ["134ilt5", "134eilt5"],
        "all-pl": ["134ille", "134eille"],
        "ess-pl": ["134in5", "134ein5"],
        "tra-pl": ["134iksi", "134eiksi"],
        "tra-pl-poss": ["134ikse", "134eikse"],
        "ins-pl": ["134in", "134ein"],
        "ins-pl-poss": None,
        "abe-pl": ["134itt5", "134eitt5"],
        "cmt": ["134ine", "134eine"],
        "hkO": "134ehk5-O",
        "comp": ["134empi", "134eempi"],  # Not used?
        "sup": ["134in", "134ein"],  # Not used?
	"manner": ["134esti", "134eesti"],
        "comp-manner": ["134emmin", "134eemmin"],
        "sup-manner": ["134immin", "134eimmin"],
    },

    "fi-decl-filee": {
    	"nargs": 2,
        "": "1",
        "gen-sg": "1n",
        "gen-sg-poss": "1",
        "ptv-sg": ["1t2"],
        "ine-sg": "1ss2",
        "ela-sg": "1st2",
        "ill-sg": ["1h@n", "1seen"],
        "ill-sg-poss": ["1h@", "1see"],
        "ade-sg": "1ll2",
        "abl-sg": "1lt2",
        "all-sg": "1lle",
        "ess-sg": "1n2",
        "tra-sg": "1ksi",
        "tra-sg-poss": "1kse",
        "ins-sg": None,
        "abe-sg": "1tt2",
        "nom-pl": "1t",
        "nom-pl-poss": "1",
        "gen-pl": ["1-iden", "1-itten"],
        "gen-pl-poss": ["1-ide", "1-itte"],
        "ptv-pl": ["1-it2"],
        "ine-pl": ["1-iss2"],
        "ela-pl": ["1-ist2"],
        "ill-pl": ["1-ihin", "1-isiin"],
        "ill-pl-poss": ["1-ihi", "1-isii"],
        "ade-pl": ["1-ill2"],
        "abl-pl": ["1-ilt2"],
        "all-pl": ["1-ille"],
        "ess-pl": ["1-in2"],
        "tra-pl": ["1-iksi"],
        "tra-pl-poss": ["1-ikse"],
        "ins-pl": ["1-in"],
        "ins-pl-poss": None,
        "abe-pl": ["1-itt2"],
        "cmt": ["1-ine"],
        "hkO": "1hk2-O",
        "comp": "1mpi",  # Not used?
        "sup": "1-in",  # Not used?
	"manner": "1sti",   # Not used?
        "comp-manner": "1mmin",  # Not used?
        "sup-manner": "1-immin",  # Not used?
    },

    "fi-decl-maa-dot": {
    	"nargs": 3,
        "": "1",
	"-clitic": "1:",
	"-poss": "1:",
        "gen-sg": "1:n",
        "gen-sg-poss": "1:",
        "ptv-sg": ["1:t3", "1:33"],  #eg. flmnrsx(z?) endings often take latter?
        "ine-sg": "1:ss3",
        "ela-sg": "1:st3",
        "ill-sg": "1:h2n",
        "ill-sg-poss": "1:h2",
        "ade-sg": "1:ll3",
        "abl-sg": "1:lt3",
        "all-sg": "1:lle",
        "ess-sg": "1:n3",
        "tra-sg": "1:ksi",
        "tra-sg-poss": "1:kse",
        "ins-sg": None,
        "abe-sg": "1:tt3",
        "nom-pl": "1:t",
        "nom-pl-poss": "1:",
        "gen-pl": ["1:iden", "1:itten"],
        "gen-pl-poss": ["1:ide", "1:itte"],
        "ptv-pl": ["1:it3"],
        "ine-pl": ["1:iss3"],
        "ela-pl": ["1:ist3"],
        "ill-pl": ["1:ihin"],
        "ill-pl-poss": ["1:ihi"],
        "ade-pl": ["1:ill3"],
        "abl-pl": ["1:ilt3"],
        "all-pl": ["1:ille"],
        "ess-pl": ["1:in3"],
        "tra-pl": ["1:iksi"],
        "tra-pl-poss": ["1:ikse"],
        "ins-pl": ["1:in"],
        "ins-pl-poss": None,
        "abe-pl": ["1:itt3"],
        "cmt": ["1:ine"],
        "hkO": "1:hk3-O",
        "comp": "1:mpi",  # Not used?
        "sup": "1:in",  # Not used?
	"manner": "1:sti",  # Not used?
        "comp-manner": "1:mmin",  # Not used?
        "sup-manner": "1:immin",  # Not used?
    },

    "fi-decl-filee-dot": {
    	"nargs": 3,
        "": "1",
	"-clitic": "1:",
	"-poss": "1:",
        "gen-sg": "1:n",
        "gen-sg-poss": "1",
        "ptv-sg": ["1:t3"],
        "ine-sg": "1:ss3",
        "ela-sg": "1:st3",
        "ill-sg": ["1:h2n", "1:seen"],
        "ill-sg-poss": ["1:h2", "1:see"],
        "ade-sg": "1:ll3",
        "abl-sg": "1:lt3",
        "all-sg": "1:lle",
        "ess-sg": "1:n3",
        "tra-sg": "1:ksi",
        "tra-sg-poss": "1:kse",
        "ins-sg": None,
        "abe-sg": "1:tt3",
        "nom-pl": "1:t",
        "nom-pl-poss": "1",
        "gen-pl": ["1:iden", "1:itten"],
        "gen-pl-poss": ["1:ide", "1:itte"],
        "ptv-pl": ["1:it3"],
        "ine-pl": ["1:iss3"],
        "ela-pl": ["1:ist3"],
        "ill-pl": ["1:ihin", "1:isiin"],
        "ill-pl-poss": ["1:ihi", "1:isii"],
        "ade-pl": ["1:ill3"],
        "abl-pl": ["1:ilt3"],
        "all-pl": ["1:ille"],
        "ess-pl": ["1:in3"],
        "tra-pl": ["1:iksi"],
        "tra-pl-poss": ["1:ikse"],
        "ins-pl": ["1:in"],
        "ins-pl-poss": None,
        "abe-pl": ["1:itt3"],
        "cmt": ["1:ine"],
        "hkO": "1:hk3-O",
        "comp": "1:mpi",  # Not used?
        "sup": "1:in",  # Not used?
	"manner": "1:sti",
        "comp-manner": "1:mmin",
        "sup-manner": "1:immin",
    },
    "fi-decl-inf2": {
        "internal": True,
    	"nargs": 2,
        "ine-sg": "1ss2",
        "ins-sg": "1n",
    },
    "fi-decl-inf3": {
        "internal": True,
    	"nargs": 2,
        "ine-sg": "1ss2",
        "ela-sg": "1st2",
        "ill-sg": "1@n",
        "ade-sg": "1ll2",
        "abe-sg": "1tt2",
        "ins-sg": "1n",
    },
    "fi-decl-minä-me": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["minä", "mä", "meitsi", "mie", "miä", "mää", "mnää", "ma"],
        "gen-sg": ["minun", "mun", "meitsin"],
        "ptv-sg": ["minua", "mua", "meitsiä"],
        "ine-sg": ["minussa", "mussa", "meitsissä"],
        "ela-sg": ["minusta", "musta", "meitsistä"],
        "ill-sg": ["minähän", "mähän", "meitsiin"],
        "ade-sg": ["minulla", "mulla", "meitsillä"],
        "abl-sg": ["minulta", "multa", "meitsiltä"],
        "all-sg": ["minulle", "mulle", "meitsille"],
        "ess-sg": ["minuna", "muna", "meitsinä"],
        "tra-sg": ["minuksi", "muksi", "meitsiksi"],
        "ins-sg": None,
        "abe-sg": ["minutta", "meitsittä"],
        "nom-pl": ["me", "myö", "met"],
        "gen-pl": ["meidän"],
        "ptv-pl": ["meitä"],
        "ine-pl": ["meissä"],
        "ela-pl": ["meistä"],
        "ill-pl": ["meihin"],
        "ade-pl": ["meillä"],
        "abl-pl": ["meiltä"],
        "all-pl": ["meille"],
        "ess-pl": ["meinä"],
        "tra-pl": ["meiksi"],
        "ins-pl": None,
        "abe-pl": ["meittä"],
        "cmt": None,
    },

    "fi-decl-sinä-te": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["sinä", "sä", "sie", "sää", "sa"],
        "gen-sg": ["sinun", "sun"],
        "ptv-sg": ["sinua", "sua"],
        "ine-sg": ["sinussa", "sussa"],
        "ela-sg": ["sinusta", "susta"],
        "ill-sg": ["sinähän", "sähän"],
        "ade-sg": ["sinulla", "sulla"],
        "abl-sg": ["sinulta", "sulta"],
        "all-sg": ["sinulle", "sulle"],
        "ess-sg": ["sinuna", "suna"],
        "tra-sg": ["sinuksi"],
        "ins-sg": None,
        "abe-sg": "sinutta",
        "nom-pl": ["te", "Te", "työ", "tet"],
        "gen-pl": ["teidän"],
        "ptv-pl": ["teitä"],
        "ine-pl": ["teissä"],
        "ela-pl": ["teistä"],
        "ill-pl": ["teihin"],
        "ade-pl": ["teillä"],
        "abl-pl": ["teiltä"],
        "all-pl": ["teille"],
        "ess-pl": ["teinä"],
        "tra-pl": ["teiksi"],
        "ins-pl": None,
        "abe-pl": ["teittä"],
        "cmt": None,
    },

    "fi-decl-hän-he": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["hän", "se"],
        "gen-sg": ["hänen"],
        "ptv-sg": ["häntä"],
        "ine-sg": ["hänessä"],
        "ela-sg": ["hänestä"],
        "ill-sg": ["hänhän"],
        "ade-sg": ["hänellä"],
        "abl-sg": ["häneltä"],
        "all-sg": ["hänelle"],
        "ess-sg": ["hänenä"],
        "tra-sg": ["häneksi"],
        "ins-sg": None,
        "abe-sg": "hänettä",
        "nom-pl": ["he", "hyö", "het", "ne"],
        "gen-pl": ["heidän"],
        "ptv-pl": ["heitä"],
        "ine-pl": ["heissä"],
        "ela-pl": ["heistä"],
        "ill-pl": ["heihin"],
        "ade-pl": ["heillä"],
        "abl-pl": ["heiltä"],
        "all-pl": ["heille"],
        "ess-pl": ["heinä"],
        "tra-pl": ["heiksi"],
        "ins-pl": None,
        "abe-pl": ["heittä"],
        "cmt": None,
    },

    "fi-decl-se-ne": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["se"],
        "gen-sg": ["sen"],
        "ptv-sg": ["sitä"],
        "ine-sg": ["siinä"],
        "ela-sg": ["siitä"],
        "ill-sg": ["siihen"],
        "ade-sg": ["sille"],
        "abl-sg": ["siltä"],
        "all-sg": ["sille"],
        "ess-sg": ["sinä"],
        "tra-sg": ["siksi"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": "ne",
        "gen-pl": ["niiden", "niitten"],
        "ptv-pl": ["niitä"],
        "ine-pl": ["niissä"],
        "ela-pl": ["niistä"],
        "ill-pl": ["niihin"],
        "ade-pl": ["niillä"],
        "abl-pl": ["niiltä"],
        "all-pl": ["niille"],
        "ess-pl": ["niinä"],
        "tra-pl": ["niiksi"],
        "ins-pl": None,
        "abe-pl": ["niittä"],
        "cmt": "niine",
    },

    "fi-decl-tuo-nuo": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["tuo", "toi"],
        "gen-sg": ["tuon", "ton"],
        "ptv-sg": ["tuota", "tota"],
        "ine-sg": ["tuossa", "tossa"],
        "ela-sg": ["tuosta", "tosta"],
        "ill-sg": ["tuohon", "tohon"],
        "ade-sg": ["tuolle", "tolle"],
        "abl-sg": ["tuolta", "tolta"],
        "all-sg": ["tuolle", "tolle"],
        "ess-sg": ["tuona", "tona"],
        "tra-sg": ["tuoksi", "toksi"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": ["nuo", "noi"],
        "gen-pl": ["noiden", "noitten"],
        "ptv-pl": ["noita"],
        "ine-pl": ["noissa"],
        "ela-pl": ["noista"],
        "ill-pl": ["noihin"],
        "ade-pl": ["noilla"],
        "abl-pl": ["noilta"],
        "all-pl": ["noille"],
        "ess-pl": ["noina"],
        "tra-pl": ["noiksi"],
        "ins-pl": None,
        "abe-pl": ["noitta"],
        "cmt": "noine",
    },

    "fi-decl-tämä-nämä": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["tämä", "tää"],
        "gen-sg": ["tämän", "tän"],
        "ptv-sg": ["tätä"],
        "ine-sg": ["tässä"],
        "ela-sg": ["tästä"],
        "ill-sg": ["tähän"],
        "ade-sg": ["tälle"],
        "abl-sg": ["tältä"],
        "all-sg": ["tälle"],
        "ess-sg": ["tänä"],
        "tra-sg": ["täksi"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": "nämä",
        "gen-pl": ["näiden", "näitten"],
        "ptv-pl": ["näitä"],
        "ine-pl": ["näissä"],
        "ela-pl": ["näistä"],
        "ill-pl": ["näihin"],
        "ade-pl": ["näillä"],
        "abl-pl": ["näiltä"],
        "all-pl": ["näille"],
        "ess-pl": ["näinä"],
        "tra-pl": ["näiksi"],
        "ins-pl": ["näin"],
        "abe-pl": ["näittä"],
        "cmt": "näine",
    },

    "fi-decl-kukaan": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["kukaan", "kenkään"],
        "gen-sg": ["kenenkään", "kunkaan"],
        "ptv-sg": ["ketään", "kutakaan"],
        "ine-sg": ["kenessäkään", "kussakaan"],
        "ela-sg": ["kenestäkään", "kustakaan"],
        "ill-sg": ["keneenkään", "kehenkään", "kuhunkaan"],
        "ade-sg": ["kenelläkään", "kullakaan"],
        "abl-sg": ["keneltäkään", "kultakaan"],
        "all-sg": ["kenellekään", "kullekaan"],
        "ess-sg": ["kenenäkään", "kunakaan"],
        "tra-sg": ["keneksikään", "kuksikaan"],
        "ins-sg": None,
        "abe-sg": ["kenettäkään", "kuttakaan"],
        "nom-pl": ["ketään", "kutkaan"],
        "gen-pl": ["keidenkään", "keittenkään", "kuidenkaan", "kuittenkaan"],
        "ptv-pl": ["keitään", "kuitakaan"],
        "ine-pl": ["keissäkään", "kuissakaan"],
        "ela-pl": ["keistäkään", "kuistakaan"],
        "ill-pl": ["keihinkään", "kuihinkaan"],
        "ade-pl": ["keilläkään", "kuillakaan"],
        "abl-pl": ["keiltäkään", "kuiltakaan"],
        "all-pl": ["keillekään", "kuillekaan"],
        "ess-pl": ["keinäkään", "kuinakaan"],
        "tra-pl": ["keiksikään", "kuiksikaan"],
        "ins-pl": None,
        "abe-pl": ["keittäkään", "kuittakaan"],
        "cmt": None,
    },

    "fi-decl-kukin": {
        "internal": True,
	"nargs": 1,
	"no-poss": True,
        "": ["1kukin"],
        "gen-sg": ["1kunkin"],
        "ptv-sg": ["1kutakin"],
        "ine-sg": ["1kussakin"],
        "ela-sg": ["1kustakin"],
        "ill-sg": ["1kuhunkin"],
        "ade-sg": ["1kullakin"],
        "abl-sg": ["1kultakin"],
        "all-sg": ["1kullekin"],
        "ess-sg": ["1kunakin"],
        "tra-sg": ["1kuksikin"],
        "ins-sg": "1kuttakin",
        "abe-sg": None,
        "nom-pl": "1kutkin",
        "gen-pl": ["1kuidenkin", "1kuittenkin"],
        "ptv-pl": ["1kuitakin"],
        "ine-pl": ["1kuissakin"],
        "ela-pl": ["1kuistakin"],
        "ill-pl": ["1kuihinkin"],
        "ade-pl": ["1kuillakin"],
        "abl-pl": ["1kuiltakin"],
        "all-pl": ["1kuillekin"],
        "ess-pl": ["1kuinakin"],
        "tra-pl": ["1kuiksikin"],
        "ins-pl": "1kuinkin",
        "abe-pl": "1kuittakin",
        "cmt": None,
    },

    "fi-decl-mikään": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["mikään"],
        "gen-sg": ["minkään"],
        "ptv-sg": ["mitään"],
        "ine-sg": ["missään", "missäkään"],
        "ela-sg": ["mistään", "mistäkään"],
        "ill-sg": ["mihinkään", "mihkään"],
        "ade-sg": ["millään", "milläkään"],
        "abl-sg": ["miltään", "miltäkään"],
        "all-sg": ["millekään"],
        "ess-sg": ["minään", "minäkään"],
        "tra-sg": ["miksikään", "mikskään"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": "mitkään",
        "gen-pl": ["minkään"],
        "ptv-pl": ["mitään"],
        "ine-pl": ["missään", "missäkään"],
        "ela-pl": ["mistään", "mistäkään"],
        "ill-pl": ["mihinkään"],
        "ade-pl": ["millään", "milläkään"],
        "abl-pl": ["miltään", "miltäkään"],
        "all-pl": ["millekään"],
        "ess-pl": ["minään", "minäkään"],
        "tra-pl": ["miksikään", "mikskään"],
        "ins-pl": None,
        "abe-pl": None,
        "cmt": None,
    },

    "fi-decl-jokin": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["jokin", "jk"],
        "gen-sg": ["jonkin", "jnk"],
        "ptv-sg": ["jotakin", "jotain", "jtak"],
        "ine-sg": ["jossakin", "jossain", "jssak"],
        "ela-sg": ["jostakin", "jostain", "jstak"],
        "ill-sg": ["johonkin", "jhk"],
        "ade-sg": ["jollakin", "jollain", "jllak"],
        "abl-sg": ["joltakin", "joltain", "jltak"],
        "all-sg": ["jollekin", "jllek"],
        "ess-sg": ["jonakin", "jonain", "jnak"],
        "tra-sg": ["joksikin", "jksik"],
        "ins-sg": None,
        "abe-sg": ["jottakin", "jttak"],
        "nom-pl": "jotkin",
        "gen-pl": ["joidenkin", "joittenkin"],
        "ptv-pl": ["joitakin", "joitain"],
        "ine-pl": ["joissamkin", "joissain"],
        "ela-pl": ["joistakin", "joistain"],
        "ill-pl": ["joihinkin"],
        "ade-pl": ["joillakin", "joillain"],
        "abl-pl": ["joiltakin", "joiltain"],
        "all-pl": ["joillekin"],
        "ess-pl": ["joinakin", "joinain"],
        "tra-pl": ["joiksikin"],
        "ins-pl": "joinkin",
        "abe-pl": "joittakin",
        "cmt": None,
    },

    "fi-decl-joku": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["joku", "jku", "jk"],
        "gen-sg": ["jonkun", "jkn"],
        "ptv-sg": ["jotakuta", "jkta"],
        "ine-sg": ["jossakussa", "jkssa"],
        "ela-sg": ["jostakusta", "jksta"],
        "ill-sg": ["johonkuhun", "jkhun"],
        "ade-sg": ["jollakulla", "jklla"],
        "abl-sg": ["joltakulta", "jklta"],
        "all-sg": ["jollekulle", "jklle"],
        "ess-sg": ["jonakuna", "jkna"],
        "tra-sg": ["joksikuksi", "jkksi"],
        "ins-sg": None,
        "abe-sg": ["jottakutta", "jktta"],
        "nom-pl": "jotkut",
        "gen-pl": ["joidenkuiden", "joidenkuitten"],
        "ptv-pl": ["joitakuita"],
        "ine-pl": ["jotkut"],
        "ela-pl": ["joissakuissa"],
        "ill-pl": ["joistakuista"],
        "ade-pl": ["joillakuilla"],
        "abl-pl": ["joiltakuilta"],
        "all-pl": ["joillekuille"],
        "ess-pl": ["joinakuina"],
        "tra-pl": ["joksikuksi"],
        "ins-pl": "joinkuin",
        "abe-pl": "joittakuitta",
        "cmt": "joinekuine",
    },

    "fi-decl-joka": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["joka"],
        "gen-sg": ["jonka"],
        "ptv-sg": ["jota", "jotaka"],
        "ine-sg": ["jossa", "jossaka"],
        "ela-sg": ["josta", "jostaka"],
        "ill-sg": ["johon", "johonka"],  # jonne ?
        "ade-sg": ["jolla", "jollaka"],
        "abl-sg": ["jolta", "joltaka"],
        "all-sg": ["jolle", "jolleka"],
        "ess-sg": ["jona"],
        "tra-sg": ["joksi", "joksika"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": "jotka",
        "gen-pl": ["joiden", "joitten", "joidenka", "joittenka"],
        "ptv-pl": ["joita", "joitaka"],
        "ine-pl": ["joissa", "joissaka"],
        "ela-pl": ["joista", "joistaka"],
        "ill-pl": ["joihin", "joihinka"],
        "ade-pl": ["joilla", "joillaka"],
        "abl-pl": ["joilta", "joiltaka"],
        "all-pl": ["joille", "joilleka"],
        "ess-pl": ["joina", "joinaka"],
        "tra-pl": ["joiksi", "joiksika"],
        "ins-pl": None,
        "abe-pl": None,
        "cmt": ["joine"],
    },

    "fi-decl-jompikumpi": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["jompikumpi"],
        "gen-sg": ["jommankumman"],
        "ptv-sg": ["jompaakumpaa"],
        "ine-sg": ["jommassakummassa"],
        "ela-sg": ["jostakusta"],
        "ill-sg": ["johonkuhun"],  # jonne ?
        "ade-sg": ["jollakulla"],
        "abl-sg": ["joltakulta"],
        "all-sg": ["jollekulle"],
        "ess-sg": ["jonakuna"],
        "tra-sg": ["joksikuksi"],
        "ins-sg": None,
        "abe-sg": "jommattakummatta",
        "nom-pl": "jommatkummat",
        "gen-pl": ["jompienkumpien"],
        "ptv-pl": ["jompiakumpia"],
        "ine-pl": ["joissakuissa"],
        "ela-pl": ["joistakuista"],
        "ill-pl": ["joihinkuihin"],
        "ade-pl": ["joillakuilla"],
        "abl-pl": ["joiltakuilta"],
        "all-pl": ["joillekuille"],
        "ess-pl": ["joinakuina"],
        "tra-pl": ["joiksikuiksi"],
        "ins-pl": "jomminkummin",
        "abe-pl": "jommittakummitta",
        "cmt": ["jompinekumpine"],
    },

    "fi-decl-kuka": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["kuka", "ken", "kuk"],
        "gen-sg": ["kenen", "kunka", "kenks"],
        "ptv-sg": ["ketä", "kuta"],
	"acc-sg": ["kenet", "kunka"],
        "ine-sg": ["kenessä", "kussa"],
        "ela-sg": ["kenestä", "kusta", "kenest"],
        "ill-sg": ["keneen", "kehen", "kuhun"],
        "ade-sg": ["kenellä", "kellä", "kulla", "kel"],
        "abl-sg": ["keneltä", "keltä", "kulta"],
        "all-sg": ["kenelle", "kelle", "kulle"],
        "ess-sg": ["kenenä", "kuna"],
        "tra-sg": ["keneksi", "kuksi", "keks"],
        "ins-sg": None,
        "abe-sg": ["kenettä", "kutta"],
        "nom-pl": ["ketkä", "kutka"],
        "gen-pl": ["keiden", "keitten", "kuiden", "kuitten"],
        "ptv-pl": ["keitä", "kuita", "keit"],
	"acc-pl": ["ketkä", "kutka"],
        "ine-pl": ["keissä", "kuissa"],
        "ela-pl": ["keistä", "kuista"],
        "ill-pl": ["keihin", "kuihin"],
        "ade-pl": ["keillä", "kuilla"],
        "abl-pl": ["keiltä", "kuilta"],
        "all-pl": ["keille", "kuille"],
        "ess-pl": ["keinä", "kuina"],
        "tra-pl": ["keiksi", "kuiksi"],
        "ins-pl": None,
        "abe-pl": ["keittä", "kuitta"],
        "cmt": None,
    },
    "fi-decl-kumpikaan": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["kumpikaan"],
        "gen-sg": ["kummankaan"],
        "ptv-sg": ["kumpaakaan"],
        "ine-sg": ["kummassakaan"],
        "ela-sg": ["kummastakaan"],
        "ill-sg": ["kumpaankaan"],
        "ade-sg": ["kummallakaan"],
        "abl-sg": ["kummaltakaan"],
        "all-sg": ["kummallekaan"],
        "ess-sg": ["kumpanakaan"],
        "tra-sg": ["kummaksikaan"],
        "ins-sg": None,
        "abe-sg": ["kummattakaan"],
        "nom-pl": ["kummatkaan"],
        "gen-pl": ["kumpienkaan"],
        "ptv-pl": ["kumpiakaan"],
        "ine-pl": ["kummissakaan"],
        "ela-pl": ["kummistakaan"],
        "ill-pl": ["kumpiinkaan"],
        "ade-pl": ["kummillakaan"],
        "abl-pl": ["kummiltakaan"],
        "all-pl": ["kummillekaan"],
        "ess-pl": ["kumpinakaan"],
        "tra-pl": ["kummiksikaan"],
        "ins-pl": None,
        "abe-pl": ["kummittakaan"],
        "cmt": "kumpinekaan",
    },
    "fi-decl-kumpikin": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["kumpikin"],
        "gen-sg": ["kummankin"],
        "ptv-sg": ["kumpaakin"],
        "ine-sg": ["kummassakin"],
        "ela-sg": ["kummastakin"],
        "ill-sg": ["kumpaankin"],
        "ade-sg": ["kummallakin"],
        "abl-sg": ["kummaltakin"],
        "all-sg": ["kummallekin"],
        "ess-sg": ["kumpanakin"],
        "tra-sg": ["kummaksikin"],
        "ins-sg": None,
        "abe-sg": ["kummattakin"],
        "nom-pl": ["kummatkin"],
        "gen-pl": ["kumpienkin"],
        "ptv-pl": ["kumpiakin"],
        "ine-pl": ["kummissakin"],
        "ela-pl": ["kummistakin"],
        "ill-pl": ["kumpiinkin"],
        "ade-pl": ["kummillakin"],
        "abl-pl": ["kummiltakin"],
        "all-pl": ["kummillekin"],
        "ess-pl": ["kumpinakin"],
        "tra-pl": ["kummiksikin"],
        "ins-pl": None,
        "abe-pl": ["kummittakin"],
        "cmt": "kumpinekin",
    },
    "fi-decl-mikin": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["mikin"],
        "gen-sg": ["minkin"],
        "ptv-sg": ["mitäkin"],
        "ine-sg": ["missäkin"],
        "ela-sg": ["mistäkin"],
        "ill-sg": ["mihinkin"],
        "ade-sg": ["milläkin"],
        "abl-sg": ["miltäkin"],
        "all-sg": ["millekin"],
        "ess-sg": ["minäkin"],
        "tra-sg": ["miksikin"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": ["mitkäkin"],
        "gen-pl": ["minkäkin"],
        "ptv-pl": ["mitäkin"],
        "ine-pl": ["missäkin"],
        "ela-pl": ["mistäkin"],
        "ill-pl": ["mihinkin"],
        "ade-pl": ["milläkin"],
        "abl-pl": ["miltäkin"],
        "all-pl": ["millekin"],
        "ess-pl": ["minäkin"],
        "tra-pl": ["miksikin"],
        "ins-pl": None,
        "abe-pl": None,
        "cmt": None,
    },
    "fi-decl-mikä": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["mikä", "mik"],
        "gen-sg": ["minkä", "minks"],
        "ptv-sg": ["mitä", "mit"],
        "ine-sg": ["missä", "mis"],
        "ela-sg": ["mistä", "mist"],
        "ill-sg": ["mihin", "mihkä", "mihk"],
        "ade-sg": ["millä", "mil"],
        "abl-sg": ["miltä", "milt"],
        "all-sg": ["mille"],
        "ess-sg": ["minä"],
        "tra-sg": ["miksi", "miks"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": ["mitkä"],
        "gen-pl": ["minkä", "minks"],
        "ptv-pl": ["mitä", "mit"],
        "ine-pl": ["missä", "mis"],
        "ela-pl": ["mistä", "mist"],
        "ill-pl": ["mihin", "mihkä", "mihk"],
        "ade-pl": ["millä", "mil"],
        "abl-pl": ["miltä", "milt"],
        "all-pl": ["mille"],
        "ess-pl": ["minä"],
        "tra-pl": ["miksi", "miks"],
        "ins-pl": None,
        "abe-pl": None,
        "cmt": None,
    },
    "fi-decl-mikälie": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["mikälie"],
        "gen-sg": ["minkälie"],
        "ptv-sg": ["mitälie"],
        "ine-sg": ["missälie"],
        "ela-sg": ["mistälie"],
        "ill-sg": ["mihinlie"],
        "ade-sg": ["millälie"],
        "abl-sg": ["miltälie"],
        "all-sg": ["millelie"],
        "ess-sg": ["minälie"],
        "tra-sg": ["miksilie"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": ["mitkälie"],
        "gen-pl": ["minkälie"],
        "ptv-pl": ["mitälie"],
        "ine-pl": ["missälie"],
        "ela-pl": ["mistälie"],
        "ill-pl": ["mihinlie"],
        "ade-pl": ["millälie"],
        "abl-pl": ["miltälie"],
        "all-pl": ["millelie"],
        "ess-pl": ["minälie"],
        "tra-pl": ["miksilie"],
        "ins-pl": None,
        "abe-pl": None,
        "cmt": None,
    },
    "fi-decl-mikään": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["mikään"],
        "gen-sg": ["minkään"],
        "ptv-sg": ["mitään"],
        "ine-sg": ["missään"],
        "ela-sg": ["mistään"],
        "ill-sg": ["mihinkään"],
        "ade-sg": ["millään"],
        "abl-sg": ["miltään"],
        "all-sg": ["millekään"],
        "ess-sg": ["minään"],
        "tra-sg": ["miksikään"],
        "ins-sg": None,
        "abe-sg": None,
        "nom-pl": ["mitkään"],
        "gen-pl": ["minkään"],
        "ptv-pl": ["mitään"],
        "ine-pl": ["missään"],
        "ela-pl": ["mistään"],
        "ill-pl": ["mihinkään"],
        "ade-pl": ["millään"],
        "abl-pl": ["miltään"],
        "all-pl": ["millekään"],
        "ess-pl": ["minään"],
        "tra-pl": ["miksikään"],
        "ins-pl": None,
        "abe-pl": None,
        "cmt": None,
    },
    "fi-decl-moni": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["moni"],
        "gen-sg": ["monen"],
        "ptv-sg": ["monta"],
        "ine-sg": ["monessa"],
        "ela-sg": ["monesta"],
        "ill-sg": ["moneen"],
        "ade-sg": ["monella"],
        "abl-sg": ["monelta"],
        "all-sg": ["monelle"],
        "ess-sg": ["monena"],
        "tra-sg": ["moneksi"],
        "ins-sg": None,
        "abe-sg": "monetta",
        "nom-pl": ["monet"],
        "gen-pl": ["monien"],
        "ptv-pl": ["monia"],
        "ine-pl": ["monissa"],
        "ela-pl": ["monista"],
        "ill-pl": ["moniin"],
        "ade-pl": ["monilla"],
        "abl-pl": ["monilta"],
        "all-pl": ["monille"],
        "ess-pl": ["monina"],
        "tra-pl": ["moniksi"],
        "ins-pl": "monin",
        "abe-pl": "monitta",
        "cmt": "monine",
    },
    "fi-decl-kaikki": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["kaikki", "kaik", "kaikk"],
        "gen-sg": ["kaiken"],
        "ptv-sg": ["kaikkea"],
        "ine-sg": ["kaikessa"],
        "ela-sg": ["kaikesta"],
        "ill-sg": ["kaikkeen"],
        "ade-sg": ["kaikella"],
        "abl-sg": ["kaikelta"],
        "all-sg": ["kaikelle"],
        "ess-sg": ["kaikkena"],
        "tra-sg": ["kaikeksi"],
        "ins-sg": None,
        "abe-sg": "kaiketta",
        "nom-pl": ["kaikki", "kaiket"],
        "gen-pl": ["kaikkien", "kaikkein"],
        "ptv-pl": ["kaikkia"],
        "ine-pl": ["kaiket"],
        "ela-pl": ["kaikissa"],
        "ill-pl": ["kaikista"],
        "ade-pl": ["kaikkiin"],
        "abl-pl": ["kaikilla"],
        "all-pl": ["kaikille"],
        "ess-pl": ["kaikkina"],
        "tra-pl": ["kaikiksi"],
        "ins-pl": "kaikin",
        "abe-pl": "kaikitta",
        "cmt": "kaikkine",
    },
    "fi-decl-moni": {
        "internal": True,
	"nargs": 0,
	"no-poss": True,
        "": ["muuan", "muudan"],
        "gen-sg": None,
        "ptv-sg": ["muuatta", "muudatta"],
    },

    "fi-decl-käsi-kulkija": {
        "split": (1, "fi-decl-käsi", 3, "fi-decl-kulkija"),
    },

    "fi-decl-käsi-maa": {
        "split": (1, "fi-decl-käsi", 3, "fi-decl-maa"),
    },

    "fi-decl-käsi-käsi": {
        "split": (1, "fi-decl-käsi", 4, "fi-decl-käsi"),
    },

    "fi-decl-käsi-risti": {
        "split": (1, "fi-decl-käsi", 3, "fi-decl-risti"),
    },

    "fi-decl-onneton-risti": {
        "split": (1, "fi-decl-onneton", 4, "fi-decl-risti"),
    },

    "fi-decl-koira-kala": {
        "split": (1, "fi-decl-koira", 5, "fi-decl-kala"),
    },

    "fi-decl-pieni-uni": {
        "split": (1, "fi-decl-pieni", 3, "fi-decl-uni"),
    },

    "fi-decl-valo-koira": {
        "split": (1, "fi-decl-valo", 6, "fi-decl-koira"),
    },

    "fi-decl-koira-valo": {
        "split": (1, "fi-decl-koira", 5, "fi-decl-valo"),
    },

    "fi-decl-koira-ovi": {
        "split": (1, "fi-decl-koira", 5, "fi-decl-ovi"),
    },

    "fi-decl-koira-koira": {
        "split": (1, "fi-decl-koira", 5, "fi-decl-koira"),
    },

    "fi-decl-koira-uni": {
        "split": (1, "fi-decl-koira", 6, "fi-decl-uni"),
    },

    "fi-decl-nainen-koira": {
        "split": (1, "fi-decl-nainen", 3, "fi-decl-koira"),
    },

    "fi-decl-lämmin-koira": {
        "split": (1, "fi-decl-lämmin", 2, "fi-decl-koira"),
    },

    "fi-decl-lämmin-palvelu": {
        "split": (1, "fi-decl-lämmin", 2, "fi-decl-palvelu"),
    },

    "fi-decl-lämmin-valo": {
        "split": (1, "fi-decl-lämmin", 2, "fi-decl-valo"),
    },

    "fi-decl-valo-valo": {
        "split": (1, "fi-decl-valo", 6, "fi-decl-valo"),
    },

    "fi-decl-valo-kala": {
        "split": (1, "fi-decl-valo", 6, "fi-decl-kala"),
    },

    "fi-decl-valo-ovi": {
        "split": (1, "fi-decl-valo", 6, "fi-decl-ovi"),
    },

    "fi-decl-kala-ovi": {
        "split": (1, "fi-decl-kala", 6, "fi-decl-ovi"),
    },

    "fi-decl-kala-risti": {
        "split": (1, "fi-decl-kala", 6, "fi-decl-risti"),
    },

    "fi-decl-kala-koira": {
        "split": (1, "fi-decl-kala", 6, "fi-decl-koira"),
    },

    "fi-decl-koira-vieras": {
        "split": (1, "fi-decl-koira", 5, "fi-decl-vieras"),
    },

    "fi-decl": {
        # This declension is used for irregular nominals, and all forms are
	# expressly stated in the template.
    },

    "fi-decl-pron": {
        # This declension is used for pronouns (irregular), and all forms are
	# expressly stated in the template.  This template uses
	# unusual names for the forms, and a mapping is used to map names we
	# use normally into those.
    },
}

possessive_suffixes = {
    "1s": "ni",
    "2s": "si",
    "3x": ["@n", "nsA"],
    "1p": "mme",
    "2p": "nne",
}
